module.exports = [
  { name: 'pattern recognition', map: '8Pwvsu1QAifWmHporsUx4f2ME3wxCek3TwWVEU9Z' },
  { name: 'linear discriminant analysis', map: 'pqVmyg7y69U4SF5c4N7aycp3nFVnQ5Ucr3pvYR6f' },
  { name: 'econometrics', map: 'JAVxvYusixLic4s3UttbzGH4BXxDsPrXEnzam8PX' },
  { name: 'time series analysis', map: 'CTbgZy8G2yGs7x4wdpzeQ5Ffwi7dMuSSPUoQ91ih' },
  { name: 'brainfuck programming language', map: 'WXVLBZhxu7bSJ8BnxZS2y2PMsssfAp1C8PuPQLbT' },
  { name: 'psychiatry', map: 'XVXH8MAqhqXpTLFDFnzQCz3rLLqw1hXb49poujy2' },
  { name: 'mental disorders', map: 'vzBhXEqv8xE9qzRi3jusBDPFgXytDchjmdxLwpsR' },
  { name: 'anxiety', map: 's4ap4fy6ZdYtZXmqKAg6nNxx6GAgcE3v1WQ8tRyz' },
  { name: 'depression', map: 'ugQJB8xSz5PJhyiMbbksnNecpqWPpcLKskgh9PbB' },
  { name: 'calligraphy', map: 'zEbbqvr72Bsq29XNQNBJQ3U7K1My3CMxMepnJyNs' },
  { name: 'generative adversarial networks', map: 'syi7FzRwkccqfD2NBvRzC4zq8zmwCpXHqjVDuz5n' },
  { name: 'mechanical engineering', map: '5FiV6jyN4HZqBKDhAFJfinDjEvXSktWxJss9Bi9f' },
  { name: 'computer architecture', map: 'VEeaqaXaB3G1yYf5ebeX9tXMqWbjoywrMdEdb5zf' },
  { name: 'kernel', map: 'jpo6SPa6Rr5qkjQC6LSqEbPVYSZ378WKnix2hhY9' },
  { name: 'image processing', map: 'uvq9pE4kpwzLBYEvU5iuriwMZbeMpAD1gLebH2Jv' },
  { name: 'cognitive psychology', map: 'Bzc24VXuC66sBNzweVKpRkuHTVsASaQNXUH1C3MB' },
  { name: 'image kernels', map: 'bUqPGfnDVBnMpUaAYuVPe3AaLJnkDkTNNsebTr4P' },
  { name: 'mechatronics', map: 'yyzzAyPcQNzKoZajEiQZixXc5AakY521af5enacm' },
  { name: 'electromagnetic radiation', map: 'L53hP87wCRcGzEExG6MfsPneyjhw4gecPBx79kBz' },
  { name: 'light', map: 'wCuxfVWy3yV8st45z9nW6JgoksmvpbeeDyWJnSn2' },
  { name: 'Gaussian elimination', map: 'fgzMe7zWaUMyggLsTBaaHLXnAe2EyXxYotyxYSbx' },
  { name: 'redshift', map: 'C1mxo3X9HLCU6fmpq7Yz1X1CvJVNoDdzFkR9fCDG' },
  { name: 'energy', map: 'LeDEpKC2ZyFcp6apYLnwu5SyE6E8WTB7AnNEB74y' },
  { name: 'algebraic data types', map: 'btbCN3cSxVKpUstzFrwK9dsQaCpxQConApGq3ua1' },
  { name: 'vibration', map: '7B6pzAdxiUYuhL5hVrqfic6TyWns5xz2uYXqtoqY' },
  { name: 'sound', map: 'jAjjZ215qXRHuG7m7QbxqCysSUz2S5tiodGYhqbc' },
  { name: 'periodic functions', map: 'yNiAXfXK5s98kdStb8KyHLvszJBsMRi4gDdGzujy' },
  { name: 'shaders', map: 'S9LpJuFLjpsRUirqygAFzSy6cgTr7SnxjhzVXtDr' },
  { name: 'conditional random fields', map: 'qBoWsidJPb7v55HqyMKoMhv8AR3s7aoacB3psxKw' },
  { name: 'behavioural economics', map: 'yWWDyx2dZ2zuaBqkyyNJ1ezEPssQhye9tHqksJZr' },
  { name: 'chemical engineering', map: 'Ph6VB5xCH4H1rFttq6CZzk51Ds91nrrcXm8xiopy' },
  { name: 'immunology', map: 'vetKzxh2UDpzBr7qKPQvcytczfSYhBongQLsamYJ' },
  { name: 'gravity', map: 'thvRU5E7kypqjLP3bxMcoUJTj734YkxkAC1zze3M' },
  { name: 'quantum gravity', map: '7Bw1MZp2zoHfV8zkdPE6zsQp7NgtmfE8QGju2cSU' },
  { name: 'loop quantum gravity', map: 'QCnWMEwMQKzfUrqzzUMeXLhqqQa5ihYwzuBzLP1w' },
  { name: 'linear regression', map: 'HiDq3DQx8Fppfxvmaqtz3wWVLMy6Dxnxm4fqjbTn' },
  { name: 'closures', map: '8mbngFphpyuFzCKfFueaWGNCtu44Ry5y4tBYzxJr' },
  { name: 'monoids', map: 'PFUwbjyxQRQceBexjjgL38EKwgyJ5ZyF7z7Vq11E' },
  { name: 'motion graphics', map: 'Ue48wxbM8CjwdJCWQNq9o5Lb8KN9wwTvx1e5ipnY' },
  { name: 'adobe after effects', map: 'bZyryqhqS3DBhgp3M7C6xsW6sZ6nYU6wnqqqyK78' },
  { name: 'analytics', map: 'jLrJECLwYCzh99b5YNUehkkgfs9HpVLptnWuBA5D' },
  { name: 'predictive analytics', map: 'pekczpvFxq9xMhofkjJTkikRXYCPhzLRCjLqJH4Q' },
  { name: 'affiliate marketing', map: 'tEtXQXerXK8xJZJwM53QDeKpwsLWbkxNwAqMvuSo' },
  { name: 'ARKit', map: 'Gypx9fupEbxBsgN6dXUwwcUzu9YG4fnaG3nTGVau' },
  { name: 'javascript promises', map: '1H9tLbqyqiaEd6ESR9Zw16WUZHusJJuDzxsfX5Rm' },
  { name: 'constrained optimisation', map: 'skWThjHLCxtgsSFkUCQ9s1PSEbPnMUMVpqPwnwYJ' },
  { name: 'ordinary differential equations', map: 'iHdxHEiFGZPRRvCBYJhtn5K2BNyxK19JAwp6YqCh' },
  { name: 'multiple integrals', map: 'Gps36QpS1LESSFXQs67sRujS6sGsTDqLq2eNudny' },
  { name: 'surface integrals', map: 'qnkpJz8sHq2Vq6qvvWy5tySsv5msosS19KRTkyNT' },
  { name: 'time management', map: 'tb95qfGH3UGcPLVgmt4P3F7unq4Rw5JkKsz5T6Zq' },
  { name: 'trading', map: 'd3cH9s5orWqhp4Fks1uTw5KFm7nJGYxE8pA6txdw' },
  { name: 'stock exchange', map: 'Yud1TyctRUkLxj6PDuyqef1TqtfH5zVYzkZfsvYk' },
  { name: 'quantitative trading', map: 'd3cH9s5orWqhp4Fks1uTw5KFm7nJGYxE8pA6txdw' },
  { name: 'czech language', map: '3WW2TyY8CytLTxr9uWifYq9h4NwPRFMnKPTVhzBF' },
  { name: 'probability distributions', map: 'zme7cJKFpqjzapGfVmvAQxKn8zE5xoXTyCfssHqp' },
  { name: 'binomial distributions', map: '8aiJc6cQjddS3yWSSubxqUdBVeE3p6yzi21zq951' },
  { name: 'Pareto distribution', map: 'eZzpJL4kzAvq9AhUdptzaPeUhYCLmNBqTWXnV3Xg' },
  { name: 'Bernoulli distribution', map: 'my49tk7BXVVshsCXeDxnTSwmgp9YBdpGTsxwxXPm' },
  { name: 'Poisson distribution', map: 'FpsX1QDR4BWPWpygcFnawvp4sX6vEUBq8Lxh5psp' },
  { name: 'fluid mechanics', map: 'b6hXzPmS71GMWKq15nfVb7U8vwUkdYqVLY2p5Nvm' },
  { name: 'autohotkey', map: 'DnjPbFDyxC5spDSPjb8qNdqp5gmVwRGv2wH7WRpM' },
  { name: 'windows server', map: 'S9UweNPxqfV4yzquyks7WpYJrp8fxZ3z7CBgouWT' },
  { name: 'active directory', map: 'tppt3GiJ5twxzxAdEJmwn9a4z2aRyUYdM5Kmwq9j' },
  { name: 'electronic components', map: 'mtKHhSLq8T39LGdoCKsyYS4uY1YtJny4oqCufykx' },
  { name: 'semiconductor devices', map: 'JcpMynyxzqFgPv5Qi4tU4q5355dqzuTz23GB74ts' },
  { name: 'transistors', map: 'VpnQkT5iNQZqxC9s9ERy9VcvFcpseitxURexb3CF' },
  { name: 'express.js', map: 'zwXmrqAW4wDks9xzpPzumULC7RGuryQCesparXZU' },
  { name: 'biological cells', map: 'PbAXx6U2EJbtsGm91ssioN7qiqrxLQ8pTDzW69sh' },
  { name: 'stem cells', map: 'iVMJXZx6f9q3p4Tqs5Dn6kDVsis5vRsupdP1Zvd7' },
  { name: 'binary search trees', map: '1jDpHatgqThpeB3fAxKJPPsJSQuDFdypHkb6BpM3' },
  { name: 'neutrino particles', map: 'UW1jP5g1NAszNQEYz4ouqPDvrpXNyxy4PAPFK7m3' },
  { name: 'symfony framework', map: 'oSMpRum83vmMvsowJtkPWzKbspZrdDAiLxb2Y4PJ' },
  { name: 'light fields', map: 'SbdABijq28yazHouwuQLdDabutCfvnqEZPyXcnz7' },
  { name: 'mathematical series', map: 'RgxzVFyYndG3gWriPBSKKQYagJ1uZjcVDz5MdY1p' },
  { name: 'geometric series', map: '2UkVqQM6zzpkeeaCJgJMqciE2PFGsfmx7KqwpjXf' },
  { name: 'arithmetic', map: 'XimK5sGQbFJy831xYyp4x5jNCCFbJ2p7xx7toPr8' },
  { name: 'hearthstone', map: '55PRZCoHYJmrjsbUx4JFbxmw9qjxwi9quQbRtjW1' },
  { name: 'dota 2', map: 'ZPKuHKoYZ9hUuvnC5VFzdDvoHqyq1ndjVJqMnowZ' },
  { name: 'GitHub', map: 'pcNLWQPSVE2DnGfTCvCawS2CcKpYzkT67kZcNYTH' },
  { name: 'just-in-time compilation', map: 'yYnKJT1xwgtab3TsHmdsivW18s6xUcisxKqQh6PE' },
  { name: 'systemd', map: 'YvVn8JSoQkHSWfvqb7dtCnv8nA8AATpXf1dyQzB2' },
  { name: 'algebraic structures', map: 'qgkC6yuaa4wKJYugQkMn8Du6XZv6idm6j9vEz4c4' },
  { name: 'groups', map: 'cL13os4msGxYt9q3spjgtzAu7PvJp2MKdKb6oxgk' },
  { name: 'rings', map: 'ycB8L66rGUnnubkU3pNc8Wp1TKi2XhsQisUj8ouN' },
  { name: 'modules', map: 'p1KfhzKg4BxicoyxUMG7quoiqRktiCM1o8GrY8FV' },
  { name: 'lattices', map: 'Nmp5D5qj6WNx8Heb6z8quxGHWVqHcwGUzswgbqYX' },
  { name: 'vectors', map: '6Gg75iLp5NzyC9FQYF81rwVi4uBqzqip8cxicFUp' },
  { name: 'vector spaces', map: 'XxYbcnyFn8bcR8N7qQFs78eNj8pjfUTYkUUSjWjf' },
  { name: 'homomorphism', map: 'pHP4zKt3kqwyayMamEnTwJRx5zKbSwAnZKF8fZrM' },
  { name: 'isomorphism', map: 'syzQDLxdjaGNVibVixYdTXUhCsqM943Kmuy9EL5V' },
  { name: 'flow type checking', map: 'SSbhAb3K5XKYqrX1Ya6755WKvCQTitbJWGJtMBnn' },
  { name: 'control theory', map: 'WzTnyVLxgbPTSykvFWqzEx5RiZjhdcLpkMGn4xus' },
  { name: 'responsive web design', map: 'SQd3ph8MmAFNCZeBYe9N3csyH28ZAokuxz9qDopG' },
  { name: 'food', map: 'pyRuYgY6zy8qcExxiPRZbB3xssLPFirsgVXPemxs' },
  { name: 'smoothies', map: '8saA91hHhZNS7XpeyVQ4PyzGQJKLXcLGfXxpusTD' },
  { name: 'aws lambda', map: '5QMbiUAfbJDz9Pww353FReaeDUDNiSUxJZNGEyxp' },
  { name: 'golf', map: '4c7nosY8nASo5Kyhzc2gzexhmB9ybssvywitsRtD' },
  { name: 'matrices', map: 'mY7Cx9QHHSdw71hkeJoeLCsojwRLMAHMA3y49UU6' },
  { name: 'dot product', map: 'pqAEToeyx3mzuJndaNMB51TaKLw4upQqvUZcfGEB' },
  { name: 'cross product', map: 'g22UUzD7AmSkKAgM24N5kNs7uxuXsE8YzTxRHdgq' },
  { name: 'determinants', map: 'QLph3xRERxJ7eSqYwsHG2h98FjxQX6jv7TbgzbsX' },
  { name: 'semigroups', map: 'psvpxgDHypYsNfhSswzmep49MDxD42cFigcaiv3W' },
  { name: 'transformations', map: 'F6NBtCQmZAJRWTyf43qfqccpYsW8hqQ9j4UENE5y' },
  { name: 'rank of a matrix', map: '3nZh4kntBwipKcHuk2pvci2qsD7JrxEfy5fVkj6G' },
  { name: 'linear transformations', map: '3ahwuxXKsPqqDFVqyKLx49Um8kA1Y3dNCu1JzUnG' },
  { name: 'red black trees', map: 'igsGsunBxQ7opKiZmuU4zDobJZ8tFCn84vTD58Gq' },
  { name: 'affine transformations', map: 'ezfFxtz9rBsG4BmqdMs2NYPCFspT7793zNbQQxdx' },
  { name: 'singular value decomposition', map: '1bydjAU1p3iqMCGY2GdqKGD2RDQyowcCSTJBbBB9' },
  { name: 'meaning of life', map: 'YsUXwnzoYKRweFFM5HGEapkPx71w54Lm8D1wiCbu' },
  { name: 'google adwords', map: 'k1q4reXu7BDymjjKKsiqyDtv6Bg41yFoMsTYctyX' },
  { name: 'agile software development', map: '6WpUA56pPmHd6hUcEfo5CKGfPcRsG771KTuyMhC3' },
  { name: 'Scrum', map: 'gVF2si826AU6emEDoA6syzuryoDUcj2M71FCZHHC' },
  { name: 'supervised learning', map: 'vZEQWXFXJnxxNB4peB2z7oqxzuTWyYsS71LYy22G' },
  { name: 'support vector machines', map: 'kuxqLwbVqNXM7yRpQT35tB7NJBGP95XBzsP21pt4' },
  { name: 'new documentaries', map: 'RQBqyQidissDxPkxp2XFv6De91Dhj1dNpJTNJJDZ' },
  { name: 'immutability', map: 'T4qnVj3Acs4VFMgspkjy46esiePrmb8yRFRCSyWx' },
  { name: 'relation networks', map: 'zKxyk4hpVA2NzhpoatKS6q4Dzqq3w6UboRxwcsyz' },
  { name: 'civil engineering', map: 'T7nc7AMbWxfGpNiHZA7xGDSyCwzv2eBuLjF7HV4T' },
  { name: 'structural engineering', map: '9xrcUcbbxQBT6dQVq8T9WxTja7yg6qRoGfZeiCUA' },
  { name: 'type systems', map: 'jcqLyxx8KFyzFBWAJAuDo7UhMJGhz2asNymxns1e' },
  { name: 'type classes', map: 'sbcvas9yTvpFEhD8YLFVzPTM1oCQQvXHN7CAqq7A' },
  { name: 'higher-order functions', map: 'UuL19ypzQeAbQvL65j6HLgp6P6ff5ynEswsF1bWk' },
  { name: 'polymorphism', map: 'p1EyvTGiSqyUmyMFHN2jsGMu4MZ6thnYkx11zPc3' },
  { name: 'unit testing', map: 'QSSStDN6MzrhZtfFj7uW5BLuCSRGpMaNTNAykqwc' },
  { name: 'heat transfer', map: 'EWkqpskPqcWjsyv6SuuzU5B5t6U7u4ZhkTyUz8qP' },
  { name: 'parametric polymorphism', map: '7QVxxcNrna6AUU3qfSjuQPzrX8K7ynDxr5Ysw39' },
  { name: 'generic programming', map: 'CkphmsAnetgGeSVwEQkJw2Z44KSsUyCcqr3mBBkz' },
  { name: 'profunctors', map: 's4jXw87itBKFioqcaxCSp8wCP1XhvSHyzv3orwqn' },
  { name: 'binary relation', map: 'vPbxSa5ZmuU5JTZrxJoZHADiVxpK7Ynrut4P2iyf' },
  { name: 'abelian group', map: 'BXAvJCZCF6Mv3XxMDZPvxKCE3BU4XfSpZDtnLd4j' },
  { name: 'harmony', map: 'pwtQ1RJBzhugqfegm4UDz2vqqLSqpKHvqVCxBxYA' },
  { name: 'hyperparameter optimisation', map: 'WNrQuQ92uUim2DwZ4UMPdsCWj2VzTpkDNrK74sMA' },
  { name: 'dropout technique', map: 'jkPEz39Sv2gNL1bbeqdvx6DMsH8tLcVPwmyVAzSd' },
  { name: 'ubuntu', map: '9YJSf2S6MWi8Ucyju5q1xpabK1LkJGxHVWgvano3' },
  { name: 'network theory', map: 'n49ig2yzjb5pyKUZTtHthq4S7parxjE7zqoUMHoP w' },
  { name: 'MQTT protocol', map: '45vkWwTbpU4UGWsYPxcNjZp5iEMzqv8iw98NRxHa' },
  { name: 'test anything protocol', map: 's25aHQQCw2qM3SszVGzXK9xEWqiGYTknm6PBjdbn' },
  { name: 'BitTorrent protocol', map: 'MRgKxhCJLmC752mZn5NY3tAsqw5gzxzt1D5npy59' },
  { name: 'WebTorrent', map: 'DxJEY6vdpFtbP4cAb7eURnLNPbugzrZy1UqBzft6' },
  { name: 'html5', map: 'zxJxCNjx3c72WB6tpzvbbuuJxQRVBgxNRJqLB2uZ' },
  { name: 'link analysis', map: 'EfRoWkz1TYGE23CuesgKgZmU9yiqq4gZUQUdypTi' },
  { name: 'interpreters', map: 'Rbip5ygSsq7U54zGf5ssb17z46y7Psenyz3FzHbD' },
  { name: 'super-resolution imaging', map: 'LX19zDapXxRvvm85xYYq8f8NxiNsT1bTy4rxGEbu' },
  { name: 'friendship', map: 'jZpAvmbkLspSv8eWpdyAAwmVoptzKs1ypEQD86pP' },
  { name: 'derivatives', map: 'uq1xfrUGoreAjpkUgexeKmp7yusxeRCtC5pzy2K2' },
  { name: 'differential equations', map: 'YUPmxhdJdvqn4iEdN1xMBNycpPLncMypHBB1ck3L' },
  { name: 'matter', map: 'LZXzNinHy3KSM5eBPHDcY1iGKCVo36e684cbSz3Y' },
  { name: 'atoms', map: 'Um11edbhnyG9jxaEp3jrszoXhpXDP6Pgiat5nvGx' },
  { name: 'molecules', map: '6yCn8tFpc2suuZst1mVYTxEnpT636ntPfJKq4UD9' },
  { name: 'chemical bonds', map: 'WMVrpJTKbpbyw8wxpYiossxJbnzKkucW4jzsLqaR' },
  { name: 'hydrogen', map: 'aMsMwFy4YazHcezzUZnYzrqBTENfzce5Uj4p5wPc' },
  { name: 'hydrogen bonds', map: '6deriGQ5GbvJqL2c2LjcNRjqZgRGfsaiKqPrBZ3T' },
  { name: 'nuclear chain reactions', map: 'XQ78NzDZqY8bDHh1uSH97mrHbWq7WqGaQUzTAGWT' },
  { name: 'nuclear reactions', map: 'UEtDSK1apVGLLHbstseNvZ8Ub529phn13mYKyzqW' },
  { name: 'nuclear weapons', map: 'xpC8FRq838vtKfUDxmtV6xfEdiTn9KYqqVzKDzWv' },
  { name: 'graph algorithms', map: '6oyRa3x6esxEtPgnb1igPuEqPxGbATcndS7xpEsZ' },
  { name: 'Dijkstras algorithm', map: 'x34BBvgGqzD5VzXZRhxSarQgR1Y8e5myjRsXdsL8' },
  { name: 'dropwizard library', map: '9744Zsq3ZUU2H8GwB97PskTosTpa5NHHKkQ7sLbf' },
  { name: 'infinity', map: 'ygthqLD3DWNS3EPHcZaJHXxNYqRsxqyi9jbDdM7C' },
  { name: 'binary search', map: 'k2xpSqsxbz27PxjCqWaFeLokmqJwwBfHTWxsrym3' },
  { name: 'Quicksort algorithm', map: 'qon6ADWpbNd3eaysvGARLneYV5Mmnwyqbx2Nndrc' },
  { name: 'breadth first search', map: 'm7aCpVqsQTWsy1cTPCvvfecEGj6ww13PJsxwUBwk' },
  { name: 'depth first search', map: 'f78pjsaRb2PaBuseUPKAtsh3rkE7HuLAqXitd9CP' },
  { name: 'renewable energy', map: 'C2BoyaqLHktGJxaoLRNt88eREjwyUjoDdNC4CTYH' },
  { name: 'solar energy', map: 'JyHpeULSPLkkQWzuGH8xee1zjtAqR8TqGotNsPjz' },
  { name: 'solar panels', map: 'UNrU496dFUx4Yptc2KsQQVx1p5wM16SrDGkxN2m6' },
  { name: 'composer php', map: 'QRsCRGfZmSZAtXp4ctqJEX1e2MbQjRVSPf9m18gX' },
  { name: 'purescript programming language', map: 'fiMdk4ZqA88sLWapCsnRrgpebuXszJnqQqridM6W' },
  { name: 'future', map: '3yHqjMRe2H3ySpxqpHotmeDREJba8DnKvszADccL' },
  { name: 'anonymous functions', map: 'PUdb3nzfzsqLDJqw6bALatixLjZTp7R2Jv8CFdpy' },
  { name: 'callback functions', map: 'cp7W7dVob3zpLcen8cr9XUSVEekLqp64mqK7CSzm' },
  { name: 'parkour', map: 'DJXGxzV61Ukpp4seN49depzw7yJMW9gGD5L4s1xZ' },
  { name: 'finite-state machines', map: 'GFgiX7X54VPAzucD9zNWt63houxvAxahuEgLxqPE' },
  { name: 'extreme learning machines', map: 'GwRNqqgrySis3m9HMeup5Sy5mstrExz12SLrrYHT' },
  { name: 'RStudio', map: 'Cp1rcsmYwJk8NTVoep3VxBK2yPtjvM4s5q6wBwYx' },
  { name: 'computer engineering', map: 'noytCG4pNNEezX7zQpWPzbZ4Mhh1qopUKSM54kJE' },
  { name: 'WebExtensions', map: 'swfWNyeQxpNJq2RUmqk7pi3NX34pZgJUzdgxnH9x' },
  { name: 'WebAudio', map: 'kabSGExdpnM4V2zEyK421WjGTxTE6qsjMq7aAuDw' },
  { name: 'electricity', map: 'SeqE9e3q4ZnuSsUWhypAC8xgXywymCdb2nQxDTiX' },
  { name: 'vector space model', map: 'yre3sP9ATDvW7Kuyzhh87LxppGTiPqcFub1YnH77' },
  { name: 'malware', map: '8nHyya1okQ4w1tPfVTsxBquHA9fR3CAW4GXf4zfs' },
  { name: 'malware analysis', map: 'jrWNHmPV4SszzjZZLsQzx7Qbs8xNX7Tr8Py2yVyZ' },
  { name: 'AMQP protocol', map: 'Yaiens48cknx2maSia3BRAzRRT6DjDqenTczqczF' },
  { name: 'RabbitMQ', map: 'FLPs7vYxc8WHbydosAhUNXMRtHuuzLw2XGSjdXza' },
  { name: 'engineering management', map: 'zzzsgWskphHuvrEE8z6gJugmrqZiWGcocqBk9Jzy' },
  { name: 'PID controller', map: 'kBhEuz41Qx92zD9W2FkuqjAEr8ucPZe7GZx4TNKm' },
  { name: 'logic gates', map: 'Kn3bqFeBnmVWz3pm1z72GCwDtwHGv8PrJqeipQRK' },
  { name: 'electric current', map: 'C9Kz5Hsw4Yvbxs6tMLWqUYRyysa2VJ55zsQQNGkz' },
  { name: 'voltage', map: 'BhupAk7pQ9TjtpoAsbCrX2nk8XpvqLtX3zvggcRm' },
  { name: 'genomes', map: 'rxBu6UT87Q6VELsfH8t2HEsmDnds5Mpou4nYMZyX' },
  { name: 'genomics', map: 'p7EWACbWyEzpaD9uFmyCqmBqNNHbr3sy9jNFVuHL' },
  { name: 'declarative programming', map: '2srz1n6NLF7182xHoSFDUDcLCiyJb1yEiHCwRBrf' },
  { name: 'software architectural patterns', map: 'riyFy7zgX5kW9kUggeBk73CfxUHSsYVSJvr4mHq6' },
  { name: 'Model-view-controller', map: 'KULXxvstqy6XDimhZ6qcpetycUzNYxrhynVNxw9M' },
  { name: 'electronic circuits', map: 'ghV7Tx7Zqox7BQZBcEWpxNqXytptm27oqxxFcQXw' },
  { name: 'power electronics', map: 'cwR71yUT5x9TKfQSkqnJ1v82N5XKXEQXL4Ef6z2q' },
  { name: 'Fibonacci sequence', map: 'ZqncZsC9qzsn64nWa7TiLQp6YWLsrPzmzNtxeKUJ' },
  { name: 'knowledge representation and reasoning', map: 'wqeqMSq4MDizrYxt4uT4gqqrwnY993x7QaMmELf4' },
  { name: 'description logic', map: '9e3aAFxX1s2PTjV9ArT9aJTXifv1NFVdXHd8EiUo' },
  { name: 'governance', map: 'ojzMZx1jER6mhuLwAckNsHUZsWNS5PSEis7zxPdN' },
  { name: 'computer simulations', map: 'pT8z9q2fZTeAggCuB9SneTtj6ioVRt4xsY1eqpH4' },
  { name: 'philosophy of science', map: 'yQpJYq2yMTYm3oTPrGkyZWsxK49yKNAhpYFePXcc' },
  { name: 'reasoning', map: 'aENT1ta1MuWrsfqJC4AJMAzQyPsnwCEbyD4gzDPr' },
  { name: 'critical thinking', map: 'FqYHSpnksQziirhPqGksLsbyT6jzEbCyyGG7gV9C' },
  { name: 'simulated reality', map: 'qe55qQzkpAa5wg9ZLfjSYBQcoPzsBCSFUkdLN9rK' },
  { name: 'physics engines', map: 'RsDwAf5hepv99FySmGXPXty2MDwbsmNz2ymzu3cz' },
  { name: 'dataflow programming', map: '5ypb7djZsT9MPuHRJgu4sGAnoAPPWKFGNq6syA7q' },
  { name: 'irc protocol', map: 'NeYN9axaEYrpQLMYiqHjaRbCwqsm4BqA7d8zPc1n' },
  { name: 'web analytics', map: '2qdn3Utwxujvz8wURPqNcxYzPro4JwszNEpMdzsY' },
  { name: 'google analytics', map: 'hCRVEZtXU4TVDN4xqqq8Fyi3qmYsQmrahyYZfn3e' },
  { name: 'mathematical proofs', map: 'ninYzqp3QpzfKTcFfKY2JWLQkqrJiWPwmwFHYNR4' },
  { name: 'proof by induction', map: 'jiSyFV6yybbx3ypd26haJckAqeBX2DB9u1DWk77X' },
  { name: 'phoenix framework', map: '96qAkztYotpx7pTZJchWBaMzHsTJgdD3PncydboQ' },
  { name: 'hibernate ORM', map: 'Ani7WwNHos8JexqWCcsSHBmtfj2xzu9z6opjmH2x' },
  { name: 'NP-completeness', map: 'yTKMzW9nNnH1zdTzvzNVECyysq8W9eDdzyzX5pT8' },
  { name: 'NP-hardness', map: 'VqZpdNsvjsTPdUyLzhrsEukzRHFQgugXx9WtbMzo' },
  { name: 'cerebral cortex', map: 'ntPpPFeQ52Ryb8w3LjDdvXpRq1XJ8mteVGqW5FNd' },
  { name: 'visual cortex', map: 'DhUzACRpJjxeKq5mCqh3BtCWYxCsuTGiZxFS7Qwv' },
  { name: 'Simulink', map: '8zqt8vXx4Zqjgvxu7BypkCnWz9NwxpMSYjxub6cG' },
  { name: 'agriculture', map: '54iCGkHhsyf3frfcds5zUjTpzXuHQcDodkLwN7j3' },
  { name: 'Flux software architecture', map: 'xyt9xRFxvmjedZmKKev7yGqztzU6qQkqJhp3mGDe' },
  { name: 'neuroransmitters', map: '25ahF4VUvCWEeGg4Spvici3y5yhGjjzhrdjtbj2x' },
  { name: 'solipsism', map: 'oixqpAaH7QZLUsZ7ogDs692wWNC849eECuvATzyj' },
  { name: 'dark matter', map: 'RTrBCmq7XDpcDD696tfs3qxNpBy4wJoqaUjqpew3' },
  { name: 'dark energy', map: 'LAz58pJG6wUyDAoKjyv9DVKcxkrNxrhsjQCQ5Rzy' },
  { name: 'astrobiology', map: 'ixx3yEohqrgrFXUA9WXraC3pSZn42VFpxNbEvqqo' },
  { name: 'extraterrestrial life', map: 'xePYSesgr2gNxfPFgrNWdekU8UvnC7XVi7zBpBXE' },
  { name: 'Fermi paradox', map: '6VCwgyQySXGQPVM2qW6rZGpNTHA7SWMvp8UEvERs' },
  { name: 'perspective drawing', map: 'B6CrcbzQusNRhqkzWpj3pQnGPp13zLyDrDz2TgyR' },
  { name: 'Bing Bang theory', map: 'FXvU7UqEKakHJEdydzsM9wnVaoxqsHsFnzixrVnq' },
  { name: 'git hooks', map: 'QwLKVq6ZJuXzxscjc9Y9NZbnpN81d3pNxxsy5nSm' },
  { name: 'socialism', map: 'WS9X5qsLEb8WyXcADssBe66iQgzysQzjGqm7Kdsz' },
  { name: 'passive income', map: 'ypeMWogv1fPptwspyqQuqBeFLTahiV5b3oihX3ic' },
  { name: 'iptables', map: '6L8dLMzojMqopG3AMixsppMqiRpkGosLTpxMLvPv' },
  { name: 'Slack', map: 'VZWYymTSrkwrXSkrF8TookxFJsayQRhDRrCRAqd2' },
  { name: 'Relay framework', map: 'rS9iMu61sVJXELujiXRcydcRstoejwtxbWKJEc4D' },
  { name: 'nervous system', map: 'gkHEToxWh4tontChwnKsyrp1VyTJ6XUsh6MYkRwt' },
  { name: 'central nervous system', map: 'VZ1EdcHErQbdtG8d7ofNQR7o5qgZqMBx8CpEHbSs' },
  { name: 'peripheral nervous system', map: 'kEhNxaQTvoNEJRnayyf5qxR9vrz7cysdcLovdAvv' },
  { name: 'spinal cord', map: 'snympTx5537R6Mq37St79DHYCvwSaebJbX2xGv2i' },
  { name: 'Galois theory', map: 'EpjbNECRGTj8xRcVneM4fhpLChyGHuKNWxiyyymp' },
  { name: 'Galois connections', map: 'xFbpkmxDYopumorbn7GZ5uX39x6AXE7WNJ7R4eEq' },
  { name: 'npm package manager', map: '9bmZLDspyMzpsB7p5vqMhmBxqXDYiDnxbUrY3GGx' },
  { name: 'sex', map: 'wbJ7KdTYNpTZi2s8uJdrKafE8y2rS13m9CBATT9V' },
  { name: 'sexual reproduction', map: 'jP5HjXhqzfWfPBazGPnqEXVd5fzwe2kuPif7Vzux' },
  { name: 'new newsletters', map: 'ien2fBGGEsdqsgcTyxYxwycNthGVEidHwNPSsCMd' },
  { name: 'react router', map: 'EpvSZjXp55zdsBBoxpBB71tW9iAFrsa8fN2sekbh' },
  { name: 'multi-level marketing', map: 'ouRYiwjGt1DoWQdmyzehVpZQgokwTD6tzchXMDXU' },
  { name: 'Sylow theorems', map: 'vPrpgi3wBgmff6sb3ibMCZwqo4dqhXLxsqm9xsuJ' },
  { name: 'homology', map: 'xhz3pCs4pX9eCR8jnuRhRRxcir27Fy666bnrtMSf' },
  { name: 'homological algebra', map: 'xNsSFKqM6gLEzgLdFjgBpkb2kn4s3yxGtxsZz6bj' },
  { name: 'stars', map: 'JZnnTFYtpgRPRVKr3h27zEGBfqLxNaQCKRbmXuyx' },
  { name: 'stellar evolution', map: 'PkYPyR81sZ3Fmqh4T3JShfUx44yjXpCCKpKqeeE8' },
  { name: 'supernova', map: 'yFovXTuxxWxhShRtNNn8CYrc2aSZMcxeYeUZVJpW' },
  { name: 'wireless communication', map: 'asjmWf1R5Eo5pMyCS3FiDkeSkmkkaPftp4Pz1yBy' },
  { name: 'computational linguistics', map: 'tdBhCdF4V1dVDHxhCLWKc9L8mgDe1836mbzpHEFv' },
  { name: 'formal language', map: 'rksntxsPPsRX24EK1Bq46u4tfQvUscqqqezBZxzi' },
  { name: 'text classification', map: '4sxtVyAoAMHrk4SJR33ZTLXsWYpuH5zqe7x97Dq6' },
  { name: 'corpus linguistics', map: 'sDrAVxFmdJ2r9qp6CmxTWL7HehLxUdsWMZ961QeD' },
  { name: 'part-of-speech tagging', map: 'gkwyBaz3KcjZG7yChnLsNHRVwG5Tb1XGfvjPPcjq' },
  { name: 'automatic summarisation', map: 'zHYYtiagqytmxJERpFYs1eTcuoNQrvCLV3MMoGr4' },
  { name: 'speech recognition', map: '9xwkwzHsSMn5RpahzEYzUEbp7N64ySNyssftyJJn' },
  { name: 'electrical resistivity', map: 'N16DQHNypkD1C8UGU5VGNdJ1nzDBCeNftqq2PQye' },
  { name: 'magnetic fields', map: 'pmYrLLssqsq2jxcnLmvvxitFxCQ4fkpTqAXn6fTM' },
  { name: 'fluids', map: '8BgjcZkyw8S2eE9vBbqXseSXsfuf8Qy1PYN1jbND' },
  { name: 'magnetohydrodynamics', map: '93bJG1X6LBd4gzryFTATjzSWPEPfsAgTsr4Rsj9o' },
  { name: 'plasma', map: 'kksTzxYpDK2KASTsARLv34qQ4FzzjQG58yoJgqK3' },
  { name: 'probabilistic programming', map: 'vetJ5UuJAY1xx2XSjkqsgByd9isogF3pZyvzz9hu' },
  { name: 'finance', map: 'ia3bJrWf9yZRwqpBWZBZd1pgeUsNttzFRRxW7ueb' },
  { name: 'financial markets', map: 'AnMzZSNnCNX83eZaWvQfQRzJosTtFUo6FvtcJQHz' },
  { name: 'technical analysis', map: 'htHpq3MqRrHjXtRix2YpyWvoCkaxn9cu2w5Ksczd' },
  { name: 'go packages', map: 'KVCZgpQPVnyasJJvaf8oSzKYvnzqsLWE2gdy6inK' },
  { name: 'maximum likelihood estimation', map: 'yF5TJc4BzLTKueazGePti4yjeo9ueZAsavP1WdnE' },
  { name: 'empathy', map: 'pNpq1qtqbhj2wRZ7NopSvyGqY2C8G5oKV7tsn4xn' },
  { name: 'firefox browser', map: 'ahEX3okEg86r3iSXu2WfSf475ubHPLMxmFqybKGo' },
  { name: 'periodic table', map: '8i61VsnoGU9Bh6Bs1aRGrzsysisZR7dYP9VEMPu7' },
  { name: 'physical chemistry', map: 'UqbdRKRL1x31dsQczVJd5smkj3k4SuvjuYUjRsCb' },
  { name: 'viscous fluids', map: 'mBpgRhYpeKhvT1x8rRkZN5Vbgwsi61gq8ATEFy1U' },
  { name: 'Navier-Stokes equations', map: 'QDmxcrKKwNxzcjUgayxSsrvkiKW8d6TGnX51nfWN' },
  { name: 'standard atomic weight', map: 'nDfpTv3AQUEfsxdxoyPpzHcsxoTtP9q7p2xjxDrh' },
  { name: 'atomic number', map: 'xze7DRJdSwp4hE1PapdqephsEVipszJ3aqRuX7fC' },
  { name: 'fuzz testing', map: 'NzoKdzx1xMnJnNNwuKSFfMDC9GdvhsexN5CjwP5r' },
  { name: 'lexical analysis', map: 'bbXCPXoseZe8VgvpBXnpCQsX7eqs8fnr5zxeDk3p' },
  { name: 'proxy server', map: 'TjjrN4R6yxgCRyznvYJZae8gbnXEJcTzQpR85aFq' },
  { name: 'Bayes’ theorem', map: 'xzhJy4hdoSNxNyNiJiMsxtz8vTDZE48FaaCiTp4K' },
  { name: 'e-commerce', map: 'kMpsxmGm6pe7MaWzARqpqsGQRonPt6e3YDSs1QSn' },
  { name: 'Magento 2', map: 'sQpmkb5zNHtqNT989qgugx8nscWQLfPszNdYyQSn' },
  { name: 'DNA replication', map: 'y9k9dNYZ3pm2QbTQyDEGPEpSfvMsefdQmyqVsqYC' },
  { name: 'batteries', map: 'XLPDtzPXowrjSXvT7J8q4aR7gqAxP5rcrp9nspeP' },
  { name: 'post traumatic stress disorder', map: 'prGHjvEMnTr8HDkHpaSLd8oc8tLXaCMoypzmXwFq' },
  { name: 'reverse proxies', map: 'DiTkTe6xMbU8gKPiyjkUGzW1be41zPeg1En4ut4m' },
  { name: 'education', map: 'qApBDpUUQypMRUL691BdzrqaQKM6yiVNMBDBW1yx' },
  { name: 'snooker', map: '3zCCqnMmtH4s6teaxzyxLExsZTrzD7qSkyxgUkMs' },
  { name: 'saxophone', map: 'qRmEXxqF5VYgVr6wAMnshGzi8MZUtXamFJkYppRU' },
  { name: 'game design', map: 'AVQsycpJzxT9z3kDyoyUaJQV2gYK6BCG9wqzPgRr' },
  { name: 'political science', map: 'xHhaZdQBqYJ5785wU8J2NLz5g3izzeD4xquppp5x' },
  { name: 'fascism', map: 'GyMWvqS8YqjEG1penizcxxuLh8DqpXRDzbWsWhKc' },
  { name: 'pascal programming language', map: 'JyN5dq1Rab1jDdD1dSM4SuZPHxo1NVomLzb5LMQ4' },
  { name: 'Delphi programming language', map: 's6xSiUPsHyVn8qqRPb7FxNV1dFhCog22gxjkg9N4' },
  { name: 'visual effects', map: 'aADxs1zqWwyCtsz9phFYjpypo4rqqrRHwCPf7EFJ' },
  { name: 'atmospheric sciences', map: '6QbshWKzANdGXqyRpsqbkPNaagYrsF38nSyBkwuq' },
  { name: 'atmosphere', map: 'zpyKpd7pPPzJ2zqXtEpYt1BhcPeaeBKXvWLVx3yV' },
  { name: 'weather', map: '9tKFRpZAhYQ6wRZFYkKJsHYz3ekyX73CNTzUMSUY' },
  { name: 'climate', map: '5DTjUtkQkrTRiXiAuq7Fw5SisykeViXCoqx6EyyR' },
  { name: 'Global warming', map: 'pePggXYbfxy31qBBWFdyqhmAH371bhAanCebcyEw' },
  { name: 'man-in-the-middle attack', map: 'sZWmfgHEAqpryv7t6s5syvgroxsxZFUqjqWxb64t' },
  { name: 'Gaussian mixture model', map: 'viPquaKDnzyXMxhVQE7zqkM9sZWuM9JCC4qBpYoL' },
  { name: 'aircraft', map: 'gsZqyDzW72soje6AqhUTNbSbKy85eQy9suz13bmq' },
  { name: 'drones', map: 'xBV78iJnpLHYSDKt7bfwywbW4u4x2dMn6ze2Fzq6' },
  { name: 'rate of return', map: 'DLhBsUggMoisGZxiJGTa2vLNfTsShapxAexEq6Bp' },
  { name: 'internal rate of return', map: 'GsrQ6hXxexMnRLe1LPAGqs98xtGVsy44snGfZthg' },
  { name: 'property law', map: 'SqZiWU6r8xT8EWhoWNMiMztkLjQSx5knyD7BWxUf' },
  { name: 'intellectual property', map: 'dzNdUnXL9X3zNtszqg1e9yzszXHccsU5EDC9GuF1' },
  { name: 'interview questions', map: 'v1TZoGvecWzqqPZRYNjT5xnLqvqvRJ6JyarpJthZ' },
  { name: 'evolutionary algorithms', map: 'bKbp6rpXsxeVC4xHPTTk1dKDJq1daANa2N1tsuQJ' },
  { name: 'gene expression programming', map: '5b9fQx3qxWURwYfpzR4sppHXgwEwsrA7E152euzi' },
  { name: 'F-distribution', map: 'visypK1rgjsYBa2qXWgkzLcM9vG9hmyDGpxaGfBg' },
  { name: 'one-way analysis of variance', map: '9revsY3LMPJRxAqkN6vBmqSMCvpyzEsjyXCZEpsN' },
  { name: 'CSS3', map: 'vywFKt4WUVms6cz9zoBsqDbshXRAsSMFUV5uhx1G' },
  { name: 'CSS flexbox', map: 'nUxJ73jRG36gaBQVMJyui8NKVn6retMEmzzjhWuf' },
  { name: 'finnish language', map: 'xs45rPpjxYn8H5QCKuCYz14zSDiD4jJXWSgzy3z2' },
  { name: 'stochastic control', map: 'vqMmpb4y1YYyhBFNfeEYaqFHBSSMUmM2nNfyyjsJ' },
  { name: 'preact', map: 's6r2X9DuxzoqMHHufvxsN8HLUWg1yLEDZfpsTfWL' },
  { name: 'forward contracts', map: '1nRUrpUyb8vG81ef9mSsPMqp99BrL2tK1qwHMhCb' },
  { name: 'futures contracts', map: 'sRHspsAfjsYYyhMvy8hQR8o6TzFeRxeqtaZTbsMs' },
  { name: 'PySpark', map: 'JctvrYTmBCiaH8nbpvSxDNpyLhCZDLqh7Vqs1hRz' },
  { name: 'membrane potential', map: 'HzAAcaxw9yWjJNVPTJwtvrfBNxh6xFSk6wo84Jd1' },
  { name: 'neurons', map: 'hXSgLbD5XiMSv1kskQxpiXsrjQDBWwpfDXXm2VBZ' },
  { name: 'synapses', map: 'zyyA7hdi28C5B5H76NQXfkcuJvKccsLsyEQD32dS' },
  { name: 'neurogenesis', map: 'oEdtqgcLTeXgKyykeuE8Fsz9hzJEa6z4KKjhcCzS' },
  { name: 'behaviour analysis', map: 'sxN1ucW3hgAyNeYEzNiMqpmoza7iP4vkmWFYaUL4' },
  { name: 'NativeScript', map: 'VAixDNeykUvpK4whng87Hosq27Hyq6ALsagcPJ8s' },
  { name: 'brewing', map: 'UzDzkB1moKxxgCz9uiJdLZhLHDuK55z1g2AbZmS4' },
  { name: 'markup languages', map: 't6NoYGEdLZqnCpL7wBbzop1t7b35rscFqYidwhzU' },
  { name: 'markdown', map: 'sdyRnTZJQMQ5o2XBLw9mRpw9RbWgJsRMunQjfjxn' },
  { name: 'Cocoa API', map: 'KSM5khp1Fx3zwq2hKwb1BzrKrW66Gd39o4M8UqS1' },
  { name: 'macOS automation', map: 'MQpeXsCQGdWeX1qnKCsYpWpfxuzoGiENTwx79fxq' },
  { name: 'launchd', map: 'VWNDn7JLyNUhUCFnUC9VnbZKeHCShs7scinMiAFQ' },
  { name: 'lean gains', map: 'xfgA2yy3XYYftsbJVfyeFsFGnoRKZ8THsw5qrwmt' },
  { name: 'bodyweight exercises', map: '4dDbpbqjyEYyLXgtMCgPVpnx3CkPysYCoHJvmpNo' },
  { name: 'ordinary least squares', map: 'QBxjVFPPHmJwQLbiUaCipLwmCm7PNVhfo3fHDRAa' },
  { name: 'principal component analysis', map: '8WrnSjxJ8ecDFdrqA3EaSeFbtHuQpyvsUW6uRTCw' },
  { name: 'p-value', map: 'caUwWzBnYPfSXpCNPig2CszsXUXQFGaqERxdezEo' },
  { name: 'GeoJSON', map: 'GDJPDSmJRwSoyZ1Myx8RVZ3BZyVR4vou83cxcKJF' },
  { name: 'skin care', map: 'CpDorL17bzJX9zwFgSfcMnpA8HZXQgGEBGDRwyJF' },
  { name: 'funtoo distro', map: 'DXessrycNQb9QQ9YcgffA8VvYhkcrSZ7zyRpRpNa' },
  { name: 'gentoo distro', map: 'piQGZGg7GghsLDH6Ts6Ev5ut77xJM76hj1eryKDf' },
  { name: 'comedy', map: 'Tir6tzsrTSqJ68vuhTf2x1ohGyj2rCpqCh2fXP6N' },
  { name: 'frege programming language', map: 'UCnnyuQfJVyz2hxqa4u2xMNmXcMLqH2p8eXHy1Lq' },
  { name: 'blues', map: 'eK4mzUfUxcwLJ88N6aMMfhsCdgzmgdzKz1VzSLz9' },
  { name: 'domain-driven design', map: 'y2zGZDqqrXtquEiA73T5a33q7S3d2WMhHk1x12iG' },
  { name: 'new ideas', map: 'NuzPCdEi4MssdSyppeAzxvqLxzKmW2aRzWxZ7Lsy' },
  { name: 'ideas', map: 'pygdU7pR8BxuxSXYF3xVoCencKxK5YbJYzabnHAy' },
  { name: 'simple living', map: 'CEVm7uUkfaqzvyDUKRSCTnsxKtzYwRBU6wTpgN5j' },
  { name: 'factorio', map: 'cm6seeVzxTjQLCkoAPkfwcMhzzY7pcUAqPWAvWnx' },
  { name: 'hanami web framework', map: 'ZzhbsP3XmYgwri9G7FzSxDZ3ZZhyH5cjRDXzB8F1' },
  { name: 'vietnamese language', map: 'xUyJbmZ4pCuJQciup2ubWPUhrS25YtezSuX7fGEA' },
  { name: 'amphetamines', map: 'p8euDosz2crHehqmXQ9JdCEp8CoPdPnw2LXCtLDC' },
  { name: 'audio engineering', map: 'yYDKTuXVi46QPrpnmNFqJrX4pDhyUvg6NWpTHmyL' },
  { name: 'angularJS', map: 'QYBozsiUWZjbqguqyKSUV3psfhganW7PB1Wapxax' },
  { name: 'musical instruments', map: 'gqiNFaWGobPy7ehkSvJ7LPtSnz93cXbqT5pwmQ9Z' },
  { name: 'synthesisers', map: 'csQtqN4tc1hzHRpqqS9zdn3bzqc59JUaxh7MwK6C' },
  { name: 'go interfaces', map: 'gsyrNyyyPwiS1wiYqMdzoDrbeE9zLphxGSXYVtu2' },
  { name: 'linear logic', map: 'E54B4hL24K8ehGzQA1nQbxChAzpyW7q2bsLMNkAm' },
  { name: 'gradual typing', map: 'fR9ym3VzCzEMNqMtCzSTNYKZ9pArhjw7pAeh97vE' },
  { name: 'process calculus', map: '8sXxupmKzvXxP8fprfUwxa9SbgUBkpeqxYw7ZFzd' },
  { name: 'pi calculus', map: 'nd2EUpPSErexy7xiGGtfKskLcbypwLGR4yHQ9nxt' },
  { name: 'session types', map: '7uraxoV1ypALnxcGgy71Zzu7t2YroAAqRPFAF5PJ' },
  { name: 'sustainability', map: 'LEKzvEJH5bVkGZZ7mePDRGuqzLxvs6HRJjRCapJN' },
  { name: 'adobe lightroom', map: '9pxzz6aJhfMVyUnKNx7AyrgToMgqLXspTE52fLW1' },
  { name: 'autodesk 3ds max', map: 'ryoBxyq66iwpWJzA9yxWHxb6bak3TtktaNzWQoHs' },
  { name: 'facebook', map: 'qL89wUHsEG3Eo8WxitqCeReeBhxUmxspgqSjvGja' },
  { name: 'leadership', map: 'kHLYeQpVebbTeVkKK23pmCc2qqwhjsxDUNspBugC' },
  { name: 'Maxwell’s equations', map: 'fycRkZyHygDvyfpJrbYf3SZziTDZjArZRsuDpdn5' },
  { name: 'freelancing', map: 'dai2AMcPtbCNQRftzjzDr6mXVyHjKEKkzzK6mqss' },
  { name: 'independent development', map: 'PcR5zxuWqcjmprYgJ4hchK395ECujxxsssqCmy2k' },
  { name: 'remote work', map: 'ahcMBpytpHXJCcpn9ySVRcfpSP89zR9EYTBR6myA' },
  { name: 'speed of light', map: 'zWYyFM6VJek1q7y2SV7pWujYuk8qSpesLSpsiqp3' },
  { name: 'knowledge', map: 'PPe92VLwPgu54ELqczArT8z7paqcPfC8gfxA1sYw' },
  { name: 'microwaves', map: 'uXnacPXnjJXqx2pR8Mk2XahBRE2xXNrcDPd243Cf' },
  { name: 'principle of least action', map: 'Suh62LeGkX9xq1PGdufCcbzqvxvkagRZYXioTvkJ' },
  { name: 'line integrals', map: 'jyRr5A9hxcdsFJvTP4EXXag5Xk6duPiyKENzG67f' },
  { name: 'harmonic oscillators', map: 'iKxuhgBkpkzknBbJ8xyHsndHpYjMjwKphqoGRaMe' },
  { name: 'simple harmonic motion', map: 'AFGhaDQKzyHsNzjnBs95EenkWeU1QkRWWEWNZgx3' },
  { name: 'statistical mechanics', map: 'zssixaZcF6ffECLtQbggvPqxyk6euyCyQnxtYfGz' },
  { name: 'entropy', map: 'c2pg3bfiCy6CzUJwq5bPzpDp9qq2DrxGy2tokAbR' },
  { name: 'Hamiltonian mechanics', map: 'bVWqh2zNCTWj8njWjSs8EU1CsKn7ueUwBfwJTyFu' },
  { name: 'electromotive force', map: 'SQdY4Zt1bwsKmwnh3UHYXpHPQygfyPQPgf4SQSUc' },
  { name: 'Fermat’s principle', map: '2tK2fMTKpk6pCWAQ1q2Lrq3MHcndjbpyzQvQwVGM' },
  { name: 'Snell’s law', map: 'fqwyfzJrfdfkYQ9sMnM2ZENDbKyZcsapsRyaspXf' },
  { name: 'laws of thermodynamics', map: '1oqBffU4LkactDJs4qDFkB1Q3Wq5NUBHJhdjhHMS' },
  { name: 'black hole thermodynamics', map: 'NevzfzFvon4sbzf8Aarfr3eQop6GAhxVWTPyazzs' },
  { name: 'black-body radiation', map: 'gKYHvzqPhoxJS8nb9XdHiehAXNcHcWRMTbPs1ddh' },
  { name: 'Unruh effect', map: '6XiAVJX6QcoSdFpaSu77iCPsAeuqet5KpTWoxBqE' },
  { name: 'Bell’s theorem', map: 'p8nRDEn2skvD6XoWTMBoBDtUCPwwSygDW4E9UQNs' },
  { name: 'Schrodinger equation', map: 'fQ7AsGTCqj6QBWjzvNzfomgQsBGwTELC2Av4GqhK' },
  { name: 'fashion', map: '5stN378JeNWspzs6M1aBpzKsSA2k5faXZpTbauV7' },
  { name: 'literary theory', map: 'qCW9SrfovvEcQ14DnkMh4wfYR2uEuWHUzFeQ2r5e' },
  { name: 'quantum eraser experiment', map: 'pRMUU8YBBVMg1X3m8pdHcpR7D7VptVPGusJCnxnd' },
  { name: 'delayed choice quantum eraser', map: '5KQauSRo5UX7hvKNiENteGdjXHwsY3aH9HzUsMnz' },
  { name: 'puzzles', map: 'xszeEKmDowXNZFhqXC1tMRKiZeN4oP9LugkYyLs7' },
];
