module.exports = [
  { name: 'inertial frame of reference', map: '89XVpRymGxqovHVXuEAPN8Pxqt8rjZ6CEcG1hrhj' },
  { name: 'Mach’s principle', map: 'AYotKYBxTetMfZZAEqux27L1Px5NsWG1KahcSnXs' },
  { name: 'matter waves', map: '1xs6dX6gr8WpHks4xjXxyJzkEADpXKPzh9FbVodz' },
  { name: 'wave-particle duality', map: '5NsmPxyyyXhgD6fsS1CLRGgw11TLMayqhr1EEeXD' },
  { name: 'forces', map: 'CxyMzyayJmVX1WymdatrbwyYUSUxmi6riAVdY7pu' },
  { name: 'work in physis', map: 'BDpoYKBgkBVmppypwyHsAnC5GsH9s8iB8bVErRHs' },
  { name: 'conservative forces', map: 'aPMyburjBmMrfPbzPX7tEXhGa2Ls5BshHP7g5pQc' },
  { name: 'conservation of energy', map: '4iZ3hq5g2UV3KtdpMVthh9H7WWxmqcBperg97yG7' },
  { name: 'Lagrangian mechanics', map: '2C6HBxDZeqXzZgC8apzj84nwWhzaxfNSzmUDBxok' },
  { name: 'equivalence principle', map: 'pW6JcnPrspdMWDsqHBeKmHZGTCpJYqy7kCGWyxSU' },
  { name: 'coding music', map: 'yzwxpE2gZi6spFZZ91TJUmL6zQ5AWPAqfauimunT' },
  { name: 'gravitational waves', map: 'qpLpC6s98K1xpvYtpUEWArEXpnbyGSTxy6N7JFxF' },
  { name: 'markov chain monte carlo', map: 'qKzqT66bXCmEgR2m2rmxz7k8Vqkg6AjU4xKfcdBF' },
  { name: 'live coding', map: '3spSxj9qRqe2fCBLy8Jo13QgsRxc4nnbuUrBP4bN' },
  { name: 'file systems', map: 'PwQMAsmSMjV7iVepEoTZ7Fgzasaa5B1XpBUWPBK1' },
  { name: 'information theory', map: '1x9J1jG7di4tUbh3y6mu131L5o3UF1RUMs493LxL' },
  { name: 'analytical mechanics', map: 'w4qVx7DzKmZbkL8LzV1ukMd82sWJ4HDYbvpBZaid' },
  { name: 'signals', map: 'u4ax1yGGXxcYkKsuxp84Mm9fnGA3NyQ6ghiszRsc' },
  { name: 'data compression', map: 'Ru5Yp8xqkvEpn1p44NF4oKWpfS2bAFBmpU67Gyrq' },
  { name: 'digital images', map: 'dvZnqeVH9Lz2hwFYRYZ4miyV4sUpxxEXEDdo6Tbq' },
  { name: 'raster graphics', map: 'fMCtrZUsXjC7TQzgbjQVzWBVkm5iTaz4SWpiELDe' },
  { name: 'JPEG', map: 'aqtxGQskzjPTnZsMe2wyXDPzdJF3hPfVtYTxxBqy' },
  { name: 'information', map: '35g3nsRBCz6yFYX8xWrrFqkGMA6yviiFyHixvF2e' },
  { name: 'bits', map: 'P54cvzs6Srewn8La4dSkxtFN9pGYhe8GhdFzyxys' },
  { name: 'Hopfield networks', map: 's4hXFVzzM4jh5q2ws61tbJXwECyfYyNj1J8nwAvZ' },
  { name: 'attention schema theory', map: 'cbcieVGZdYxFMp2QhVgaa6QYJvPZARhG1LsTxpkJ' },
  { name: 'microdosing', map: '33n8vA1xYkHWDFSYfpBoFSUzd4Z2gCeo6tpxFHqS' },
  { name: 'watercolour paintings', map: 'YtqdbvUFHEctPZJuzNZ3ZqWCX3WrheyD3KxQVLC4' },
  { name: 'coding theory', map: 'jY1BwCSzyozeoyfeUyteyANNCeowdpgM8T6psJPx' },
  { name: 'mobile applications development', map: 'sTrCSdicjWfWfyQLPeyBsL3M7SJuMqAjT31Vswx5' },
  { name: 'Ableton Live', map: 'jFU1TtdsYvKsYbCsh3T83ZbzJb6K2xmbkeQ5yN3y' },
  { name: 'polymer library', map: '2MCnmHzyp7sw7yPcykEveYqqbryAG5MHUPjEdzmp' },
  { name: 'influxDB', map: 'Wq8Ut28LgpySZdSXSrpdYqoHAs5v29mLydTctzZf' },
  { name: 'harmonic analysis', map: 'sQm6Zgx5Nz7y8jUU7XRPtyGucQFQyresWwRWFCoM' },
  { name: 'Fourier analysis', map: 'wyAP4f8ZeW3WRASBapjyyPJbs733jsBbsWuFKvvA' },
  { name: 'numerical analysis', map: 'EMutg8hCqAGsTxLf7aW8WYSa9paupbXdaqVax3xn' },
  { name: 'evaluation strategies', map: '9pDZzpWfNrzPeLyovWYrwvq7rfvUnctLxdnjNTFm' },
  { name: 'algebraic number theory', map: 'MZ5qGp2qWwZShsMLs8hVBAAbuZZXzXahyaq3qsja' },
  { name: 'trie data structure', map: 'zpi84AvxkQKz7EX6z5efdSThmqBNGRvsC7CiDWEi w' },
  { name: 'inverse functions', map: 't465zbtkZkEyPpx24GWPxxhqum84rdSzzLUs5dAs' },
  { name: 'decision theory', map: 'YqfsAzb4fqLFyY3LXYmQSph5rysgyjeiDtJw8DVe' },
  { name: 'categories', map: 'RmCNrFfTKsrNLUNYmxrkqq7Nhg3Pi3HukreFhi9u' },
  { name: 'topos theory', map: '8efUY8RaEhi5vL4GNCY4TgFykpZyW1zqp2WgiSR7' },
  { name: 'multiplication', map: 'PxsrpBk97RF9LLjiKpZRzottfm5FA9AMr5yZXF9k' },
  { name: 'exponentiation', map: 'iaHnrySuJnsXJTUzdZcddpFxpT2AqFHyjrxZPoJg' },
  { name: 'logarithms', map: '8DeEKTuZprx3byxvUJmoFyqBK8cYc9krjVqptBz9' },
  { name: 'modular arithmetic', map: 'KHds2cKn6b6tGkySXtyMsESLdwshhXVm2H1mqabq' },
  { name: 'journalism', map: 'mZVx2vx3WgWqocV9ZNySsFZ15Dirnzdswp5V6zYy' },
  { name: 'freedom of speech', map: 'nz6A2DbDML4vc4Ns5suf4zFzGry2eSxzhU5dxaH7' },
  { name: 'conditional probability', map: 'UtaFiiR4M24aWKTfjoX6SDhfsgQ9BeopaGQd87xj' },
  { name: 'trigonometric functions', map: '5sfxHzKTsYJKhZQerZy9zytHfNszDQdHycJb3rBs' },
  { name: 'quarks', map: 'r4S4EvS92fmKHAnszpP1tzzjr5fNEdysAKDgiVV8' },
  { name: 'network security', map: 'yEDQPFZjUX7Rn1y1Vy1KppoutF6ybp7eP6mqdUVy' },
  { name: 'phases of matter', map: 'NMirPrPCNqtzJDFH11wqz18ox2ZFEdWxRuP6s7n9' },
  { name: 'cartography', map: 'rbRJnYtL1aJ5hunvazskJDZaywjKpUcAByghqYpJ' },
  { name: 'topological order', map: 'wrJ4wAgYDrJAUZ1q2t9yPrsfZkJgCPwmpzYE4X7f' },
  { name: 'topological sort', map: 'JmsxgZyQrzgZDsmPbPKCbNHEffLtj7NxWvWiyNyM' },
  { name: 'merge sort', map: 'EFfW1Kpxk7TpZxxnDya1SmqGwpW49uvawaqEbND6' },
  { name: 'selection sort', map: 'sEGYp5prquKGFcZvFmgeFcy8F4rxsyKjoU4Ga4ux' },
  { name: 'nanotechnology', map: 'EdVR4qsppRXxkwMp8yuUQFn41YaF3vz9gbkL9nUx' },
  { name: 'molecular nanotechnology', map: 'ug5jbqyMg2jq3f8FxZAUrTrRy5Jq5MUdxpz6HkEq' },
  { name: 'molecular machines', map: 'egxzzdUvVLzpm8wpykk3yCxBy9BxD7injNmsA3ac' },
  { name: 'neurological disorders', map: 'Y117DmtKn7zqz4gyufHzCMUv98uz4tUsYGc8Tgku' },
  { name: 'epilepsy', map: 'ngzk9HbfKCruaVRsyyQkgzRst1SLptmitYKxRRoP' },
  { name: 'neurogeneration', map: 'hXqyKCWRdwJLdfSQ1svQPVZH445xLZabdmMdhjsG' },
  { name: 'Alzheimer’s disease', map: 'MPLQLFMkb5PCWnziLM4136hsVgKeMKx7hHgMZDQb' },
  { name: 'Parkinson’s disease', map: 'uWS98CAXpLmqA9ZXzwgAzv8VMW9BVihWmXgz7xsL' },
  { name: 'stimulant drugs', map: 'Yeyie3oUys2jFS5zp4qhjmuhjiKDwLFppTzZ9m9R' },
  { name: 'antibiotics', map: '9wnotpuHavxbZGzs1b8BBW4f1bU5uQEYySJYUvGy' },
  { name: 'penicillin', map: 'ae4U1mJds2pXdFRxxZkBXqWHgx7bSa3uEFLmykqW' },
  { name: 'autophagy', map: 'goP4fW5Y2cbc3aTM8Aea2aeFsWo7N8NseQ2HytsS' },
  { name: 'cell division', map: 'MT1tnQPDdqAPDzyEeCjJCr21Uu7vSEEiZYBro6gf' },
  { name: 'cancer', map: 'jepopC6ssQg7z991zJWxZHY4d8LWGzQUvcDuWmjn' },
  { name: 'contract theory', map: 'jMRzeR8UWH5cBXxwiFPwm2urLspq4WCzG2ELS2Sg' },
  { name: 'neutrino oscillations', map: 'k1fcsmwts5fZ6kkDebr2bgC8Bq358zbaXMq9nxjq' },
  { name: 'DNA repair', map: 'PxmFhtQodWyYnyZ2JWqMpNenQxtxCuu4viCKTbYz' },
  { name: 'mixed reality', map: 'ehv9iYFKz9G5RSxNAsLF2mYGWA4sH4UpFFtorQyV' },
  { name: 'marxism', map: 'bsNV6EssdaAZs1Yko5DdLBUgPUx5zqVpL9g6T7G7' },
  { name: 'cinema 4D', map: '5LZNya1o63Gcsp2svBTwwCAxKy4EiBv2Pqvzp8pC' },
  { name: 'software specifications', map: 'VrVDF8ySqydfKfFxUy5VyqAZBQV5gC6x3W7isxue' },
  { name: 'plants', map: 'aqf1BVmT1hLVJAHzSqQyy1P3ytKUABs2soRymHMa' },
  { name: 'hydroponics', map: 'Ha4yppJSBC2xP7pjzbzCh8FdZmq6aDWNKWaqWUu3' },
  { name: 'kinematics', map: 'WeAtqp57ipF4sKJXVF7PwudSb3DxBgyXwomVz7Q4' },
  { name: 'code refactoring', map: 'J7ye7TjSYwrcfuZY2D3FEXGytQxnbFzxpqj7PJKS' },
  { name: 'Kruskal’s algorithm', map: 'Cz98T8mqWqeZkhDH3U44Z8HF38b8uvWuicJwYzor' },
  { name: 'Prim’s algorithm', map: 'pMxtTtR2Ygq3zAQTAYqCBozfHe3FoexG61xqiNEG' },
  { name: 'string searching', map: 'n2UQ9sBQgzqkss8R2PqamzKZsxmpgY6vPUb5CGbA' },
  { name: 'Boyer–Moore string search algorithm', map: '6BijwPdzqZSC7BkyEvAJVoVySwvvVVQvu75pqsqR' },
  { name: 'truth tables', map: '15PQgjxf6SgeLRpmnr1ZEPwpKgSStz3TNpw9yqtJ' },
  { name: 'crystallography', map: 'vM6ek2Nxskk7WxsSLxpz12ZqHcis7RMxeuTWiv3B' },
  { name: 'RADIUS protocol', map: 'Zzo61w8CnFxwVx6Esqu2j65jqKKATDxSHJqi1qkf' },
  { name: 'crystal structures', map: 'kX3SdqRS24bv3NvNHXqHqdxAXe9XLnDrPxsBiegs' },
  { name: 'quasicrystals', map: 'xfCE3RNduVJRsdNEpTxsjXt2LzLqc9yRiyVitp35' },
  { name: 'branding', map: 'sBBx67GukVYYs4Uki4s1PqjrJY35jEJWe8xpBu1z' },
  { name: 'cloud computing', map: 'LzjyjVYrG71xcmnNarSMbYAhR8ip58z6eS3fzfo5' },
  { name: 'continuous integration', map: 'Spim2n6dSkxHVpLwYZDWgbKzwwwKD9LEpTpJH3ru' },
  { name: 'mojs motion graphics library', map: 'xsB62sMiy2eeZnJVuXfNsWHfQv7Vym1sgTpKGxpZ' },
  { name: 'chrome dev tools', map: 'd1BQTwq1d9n3UVFWgxzfExqmXzkq6ZzHFT2SVTf5' },
  { name: 'debugging', map: 'F8Y19sWJLSVY6ZxvFRJgjZKEGx9cXH9DpkRxWujq' },
  { name: 'startup funding', map: 'jmNdqeJVEAsTaS2SFA3tsDWV1kR5mt9QzPxviRm2' },
  { name: 'evolutionary psychology', map: 'Khs72YTodypfHLXzx242oDzr9pyg6VyENipKTN2h' },
  { name: 'creative writing', map: 'TttxKDFfhjjmno2yspaxYiDHZqKKz6Xqqd2rhyyg' },
  { name: 'fingerstyle guitar', map: 'ibCbkmKwyxUTGmzxBhiF2uU5GuHpxXgDv2dUMNbc' },
  { name: 'spectral theory', map: 'LxnDuZ4mYiNxP4Gd6VEx3aUKE2PJhoWGsiUd1SRh' },
  { name: 'texture mapping', map: 'MrGas8o9VhY54GJvzyzQWwqp1TQzAX5vwPhYsoR2' },
  { name: 'event management', map: 'r694FjzzGrt8U1udfDsnDz7jLxsW61xiHBasRuWH' },
  { name: 'loss functions', map: 'zvZX4FNytFqdhLmuCHoj45J1tinLKjeSMbQ6VVpR' },
  { name: 'cognitive biases', map: 'csqS9stf64qzDgtDYjGgaXe8TqZJjqJq5zLq5YqR' },
  { name: 'cognitive dissonance', map: 'cmk4fh551FmyBm5Eg3vAbj9zruxk3W41XNreG4v' },
  { name: 'social skills', map: '2ymNKBdN4BwVNZoKscDRCNXzfqLwMSNfqRw4pkye' },
  { name: 'unicode', map: 'czya73CTnyt8XsuzqrqxwHcprEQK9M14x2go5gPf' },
  { name: 'hamming distance', map: 'S8dUw8zJ2wa1yVgqFz1fskWjJzqG8yoQR1wRHvp4' },
  { name: 'XOR gate', map: 'g7Tkng6qCZKvVpS2gZYxicMsfMcEXxDaDUbp6c8x' },
  { name: 'kinetic energy', map: 'dp5a4RzDXk8tYouubdzRCWKFsBfWj549ATTr86wr' },
  { name: 'motion', map: 'sp7TkmsLaDQxqgpLQsvBALs2DpFLYKfvfMnqsTBb' },
  { name: 'linear motion', map: 'pPNjX9MB6ithWqexhfmQihkAZsQSeogofeoUZqKa' },
  { name: 'momentum', map: 'ms2YbNd59GTG83eBLrDaG6XP8acaxEWywDHWpDrz' },
  { name: 'angular momentum', map: 'XXsjA4wazmvuwn21Bbpyd4nTXft8NzzWzXRp8vrQ' },
  { name: 'economic history', map: 'Hh9zyHQFf3At4UsS3pVNB4yABq7odg7CJjzRbftB' },
  { name: 'mechanical equilibrium', map: 'SpsZ4UqHvTWzkXG4wcDqatfTE5NtFnpHKVZokitw' },
  { name: 'photosynthesis', map: 'xhMLhLYvpKE1ZsNL8hLxR8sJSEJjzuaDRoZqqKqi' },
  { name: 'potential energy', map: '6LxqzY1ikTfGsaazQ2crxB8UxSYpyCQGHpfEtHsQ' },
  { name: 'adobe premiere pro', map: 'UgxRsKGqvKzixriBHyRzVAXDEYqH1BsGpF7XBZGZ' },
  { name: 'DNA computing', map: '9UsRN1u9bevjaxPFntjwtzQiazdxaUAeWFoecEcf' },
  { name: 'evolutionary computation', map: 'VfuGudA1ZBCqwwjiHyuu4SEucy5y4jxPWwibvysh' },
  { name: 'morse code', map: '8EqLVWppWgsRUcgra8FoAfBCTX16txxcWfrbtA9e' },
  { name: 'interactive computing', map: 'AwRTP4as7mt72BFKCTkqFTfNhyNmDSuqpTN23hSe' },
  { name: 'Jupyter notebooks', map: 'mNzURzwrsBpsqDCTqqyK6sypPF8ApC7rfhwxKSsS' },
  { name: 'puppet configuration management', map: 'd7UfkvGCqgmZpnLX8PpypRxsg3dsQWyqns7gwg7q' },
  { name: 'CMake', map: 'jqYuC8bcHKe781zo1Bsx95Uoxp2acf3ZiRxUpETy' },
  { name: 'malaria', map: 'Ht1AscyHCGY7GmWARjbjH5hki9mZinHTh4WdXddw' },
  { name: 'schizophrenia', map: '9Hr1pHsYVBD5ky8xr4uBWr7jPzmsp43aLQosFyCL' },
  { name: 'diabetes', map: 'AJzScQ5hQ6iBaXHpLpxXzRBgPxun73oGYvVdciKH' },
  { name: 'HIV', map: 'NXdczhgbpmYbJ5AkGanktRK1eW6yhJHqbgRz2jyF' },
  { name: 'influenza', map: '3igcVCXipErFygZy21WwjvfqaQkU13qxGbEE1Ten' },
  { name: 'tuberculosis', map: 'opXtVhyVGTV19TuHpKYUbAN6yvt3DcuFFKbSiMQm' },
  { name: 'nnabla library', map: 'CwkzqyG8yypsZKSomVWviKx6nsBB9xbRxuaiqoHc' },
  { name: 'system administration', map: 'p8GZ97vV7RR32p42pnJQbXH1QeF2nrXYje4TdywP' },
  { name: 'harmonica', map: 'R5ws3umUrqBPZpyXNAyLCEoeRYeuzusjM1qDtENr' },
  { name: 'openshift origin', map: 'tsg8CJDALgBMGjguSTy4W83hMKbZxuFxxD63SNHX' },
  { name: 'pharmacology', map: 'FiZCCism6MpCos4zEy19YcmHqMgp18aj1Fy67ErH' },
  { name: 'path tracing', map: '4urox8eyCpZY5UBmCtGHVZ5vzVLgoeGtKvsgdNTi' },
  { name: 'Qt framework', map: 'zFgh78qkBQbkqFTJaKfhopnsp3UascceN6PCmTVd' },
  { name: 'FreeBSD', map: 'iKEq3yqQgKqiEkoTq8bkcA1Lsxs217FGVbvRrxKG' },
  { name: 'interaction design', map: '61DehkAXdcqPzDJDnvRqYzEyqR7T3SjBP1pfous8' },
  { name: 'Xamarin', map: 'gVywARPMQCPNbBBAwYszzip5Sp45SXyeUbeqFCey' },
  { name: 'salesforce', map: 'jaFJzDmo1kQDMSdEKcyrkzshrsyUkcf8jyd9xYp9' },
  { name: 'heroku', map: 'fzprrVSairk8ugNKs9LU7u8BHmgQqjaMN4AkYS9X' },
  { name: 'digital ocean', map: 'LWKzjnG6UFzMMpxyyj18KNnavyQuvoeDAosbxrmT' },
  { name: 'real estate', map: 'yDQidEZ9rWH9UzJKoWxwrcUbgyayasrqvVizgcEq' },
  { name: 'new tv series', map: 'NpbsMkqDKUzGEyzHFqHBdegAUQjKJzus1MDxQcqJ' },
  { name: 'kerning', map: 'Mcw88khk79yenzeqHn1oh2RxAMewxsspurdsiyqy' },
  { name: 'android studio', map: 'LnQ7iyWznpvHGPcn4XESBZU8Yh1SRppQKYwWzvo1' },
  { name: 'archaeology', map: 'hCDcpxsWv4pzqecrf1snypFNA3XwSKYcAxBghHhV' },
  { name: 'JUnit', map: 'DRCgcboqbpWyqpzYsgiFG4xix35z91b4x1zRXtgW' },
  { name: 'CocoaPods', map: 'mq7WhmAXq911vEt5J9uqP66gq9yBgvYqcrARxukq' },
  { name: 'swift package manager', map: 'fmcqFKUXvppu5WGaS8yozBcgxNobZZpj5N8A4Gc4' },
  { name: 'swift libraries', map: '58muNxNAxekvkmTqGZ1BebzgpkdSBfx7Dg4zAzBU' },
  { name: 'RxSwift', map: 'mQGnLus82LnEH4fNsYHMxGoCBpztahtLCZy6Ypsy' },
  { name: 'Fastlane', map: 'y1ozs2orpzUbx8x6wpdwYMrz6dxPrMzabaz3qmty' },
  { name: 'headless browsers', map: 'kw1NfUi1SdmtuxqLsKz2nKS2AVE2a8hgon3XhUuR' },
  { name: 'WebExtensions', map: 'xS1mVawVtDYu6yp9ZKvz49WGR7M7Gm8w2UghsCtW' },
  { name: 'python asyncio', map: 'K4mrWyq4V3FFSoXVJa7cqihX4TJWqZZ8gyMdTWSm' },
  { name: 'html canvas', map: 'BqbDaZdEb8ZDzTiv6f47KN9xspzXm66bqYpv73Vw' },
  { name: 'discord', map: 'yYb4SzR2pm4zezC5tAkRqi8KKqBG3rweTZHpLsHy' },
  { name: 'telegram messenger', map: '6kJhDhmdD1F7eZGjvrtcsBWFpJpS1Mq9V4avhJka' },
  { name: 'emails', map: 'axdbHX76hZNvjoPymgMCipsxmMbYXmtyFbmCfpqz' },
  { name: 'offline first', map: 'jFZuRp2rDX1miapgHxioUn4QGDpHiJsHFGfzpk6F' },
  { name: 'program analysis', map: 'jdKsypzB8Zfk5hDeraCD9Sq9aAkgZDxfQXpPfEnz' },
  { name: 'static program analysis', map: 'ytXBx8uLUpg3QqdXYMVmqMziF6cjQaUvMcjdy7AR' },
  { name: 'development environment', map: 'VmsYbPx84hHLHZBgx1epqT3dbX5m1RJLAfX5Ry71' },
  { name: 'dotfiles', map: 'nzpDH7L2bkLsBSqv5cCQtVTyc1zLJehqRspUL1dT' },
  { name: 'cell membranes', map: 'TzpnL3YgxVH98VbtMp3PyfJ8pyyabpFjevksNmmz' },
  { name: 'homeostasis', map: 'Pde657KBLahui3ESNuzxWqj67qaaxQHkcn2tkrVF' },
  { name: 'hyper terminal', map: 'cnELLqCs6yhp2LnqPMiGts4X5UtS5tGxxBEgKqxV' },
  { name: 'new quotes', map: 'zvfqYyTyuHiwnJ8AuZPY1xmmvfNprnp1KNQJ4Qyw' },
  { name: 'quantum electrodynamics', map: 'EA9muTAPzZpBfhRsQRgaiUZLsaafozWrPv327ouh' },
  { name: 'visual system', map: 'siTZtxAeyGy68iK2Qykcsq7o4keykybSx8kArxqV' },
  { name: 'eye tracking', map: 'byLz81zWyLPwqsA2qJiAA73jRspb1HpbS1KU5jwu' },
  { name: 'vector calculus', map: 'fiSxzbZuB58xV2GJ7PjXL3TqsWYyDCgqKHoKzkbn' },
  { name: 'vector fields', map: 'ffLzx277E1s8vi6aqEARK9Zj7gLNMb6MKn35qUfm' },
  { name: 'geometric topology', map: 'zQppyWDFpyT4tq83fnYMKqJdUJXL25eVwHDQUu5b' },
  { name: 'realm database', map: 'SVxtpr4sCBWPZXJ9D3LyKzfJyNhNdcmHxzNyWy4e' },
  { name: 'eyes', map: '3u6imyt5ZZeaoWi4wfEVFLaMbpzDsp3kUiy2r1yp' },
  { name: 'pupillary light reflex', map: 'PcNtJ6yKhUhetHJDPxvtkusvd6Qzc9BjLtvvyVix' },
  { name: 'reproductive systems', map: 'iVHXetZYYRdNyHTy1wqAy9PZzLLAfXquihaaHJ9E' },
  { name: 'immune system', map: '2wy7LCsFSoUMA7aWkdttpaisM84kMZ53AiT8sLxL' },
  { name: 'blood', map: 'bH8s8V6LHzyWUeDTth3xpofspsbjDx1AC7YhRmpW' },
  { name: 'human body', map: 'Yyiq3JzpJwq1Q1Bpe3C7Mzay262qpjhxmTpmph5T' },
  { name: 'respiratory system', map: 'B2xrqPJJMuysipK9sH2DJiz4zkFcseBT64kJzrza' },
  { name: 'digestive system', map: 'yagaqYDmMRztdZpWCCiQLsBPK85iCBmp3eAyZswj' },
  { name: 'endocrinology', map: '5jagg8gz2DLimDJMqWByG86uR3osV9TeGy7HyiGn' },
  { name: 'inflammation', map: 'DXvpwPQyQVXSE87sHy9Q6aZnTD1QtcyFEqbpBAbz' },
  { name: 'symptoms', map: 'znEy9T3mvM7BNenAx6zZnbak7v5HuiLDFDCVpeSo' },
  { name: 'pain', map: 'YSbgRFsjyLcPT5wMC4J1YaBep2s6phXrvEY7zXMA' },
  { name: 'microbiology', map: 'yNKhxqP1Cog4gJ1WmpFewLTPL2nb5tTho5NZavps' },
  { name: 'new talks', map: '2ywtjxDtvbk6fPxu794xELDKMcA2zuCKFcAPmrMs' },
  { name: 'MariaDB', map: '1nvNgqRhs3Ef6q1Zy2ZMiUttPx3bcyR2p86EL5g9' },
  { name: 'cryptographic hash functions', map: '9Tx7VQHpTrwUJtf1x7rcwPyt7q3vpM4kiMTws1qA' },
  { name: 'SHA-1', map: 'dxci55wMw5NVoyP41DUJbCxoyXQhpa9uGWr4tMyY' },
  { name: 'end to end encryption', map: 'y1RBVPdJBVWoYz1hDN5NURy34sQp2TyMSaoqnPqS' },
  { name: 'SQL injections', map: 'fcpb6j4gpssaBFv4zCDabRz4YVkmJs9sPVWLD78t' },
  { name: 'cryptanalysis', map: '5mnsmbWz15EQY1XgVZPtE123z9u7PHcykXmXXWhj' },
  { name: 'authentication', map: 'ciaxqLS74KGNcoC93dJ3U2YpFh8kWRA5wAMq9Nzz' },
  { name: 'passwords', map: 'hzAsvpveCknTvxZuRpbtxm4Uh4bxqzeGaxqqgMp8' },
  { name: 'password cracking', map: 'c6yHRBsDdxxfwS9G6JjUosBYs8AVapgkmsRk14yz' },
  { name: 'buffer overflow', map: 'DrSpt11xhuzrYHJ3akpsqfGY9jCopsEck6MsnzXr' },
  { name: 'combinatory logic', map: 'LZzCDFtPer8Aq3YSNpP3PrhSzVZkQRPx1dxMSp2Y' },
  { name: 'polish notation', map: 'xfVvk5LUpADHVdj7yMsWfxVYGiEZBLuM9SiidU4B' },
  { name: 'steganography', map: '9GeejS1b1sQ4wsZo4sy3frtgZjHpg3oqNdjYGz7H' },
  { name: 'fonts', map: 'hqwshdgeTtTz4Fgo7hsspsh3qazTWTqJvocthssu' },
  { name: 'transformation matrices', map: 'xa7dzFqFhGmoiWsRx71tPo7yiy93YYjrGGWHYQvy' },
  { name: 'computer graphics lighting', map: 'eLJvNJ1FsdAHh1Y8stmXiDHkKsEnzLPUujAEFQBF' },
  { name: 'bootstrapping compilers', map: '8qmT8MPtYMWVzh9vsTeYzEPeJt1VqPJM9xejyAt6' },
  { name: 'data storage', map: 'BBcyivftgisVStXUJVF6Fa35XZJpv3rpoELsmpuu' },
  { name: 'DNA digital data storage', map: 'hEtq76EZtD3tAZDzv2nbJs83F56k2KHmKNS39Lxq' },
  { name: 'hark disk drives', map: 'GRNpRXzdPPHvCnFBpq9xRsg99N4p2hHNUiXRZgpJ' },
  { name: 'solid-state drives', map: 'Y7xgsqxNBh9xykrMV2YDp7zH5S6bKF3TQp8VpYwA' },
  { name: 'punched cards', map: 'JJuEcQsDLhBWjLzEQE5QbxEDYN7qX9tZ1NPU2sB5' },
  { name: 'concepts', map: 'MXBBYiQpnQAXkdyvX4fwFyeZFnGPpxN6FJwaMyER' },
  { name: 'abstraction', map: 'bFGwpSqSjpKsBppoNoES92RpjVtNHhRCMABFToKK' },
  { name: 'information processing', map: '3GMnBiZiqAocp9AqUpMexyVqCsPTAGU3Bs72cZWp' },
  { name: 'prefix codes', map: 'Hr7gS8xfBzWexKd6BYYNFYoGXfFe96WDb97V7n3f' },
  { name: 'Huffman coding', map: 'vUYAxFyQRkofxLyCeaM48ZRjybyW6C3p5UWj18NZ' },
  { name: 'documentation', map: 'pFbNGbWq8UEyEk3v7Go5Se679fBxqozb9Kw6nm6q' },
  { name: 'human computer interaction', map: 'sKMRveiqWCXS5nckv9imSPsFpwuynbqSoDi2qtes' },
  { name: 'cannabis', map: 'CCbXzwyoTScayHcR7RbGqperUNAENWcwR5VCX6s6' },
  { name: 'psilocin', map: 'vNLd9wodETfTkz61WgHLrvgzbyyM3XAwiZ5ExqRp' },
  { name: 'mescaline', map: 'HpxwgjxzHS4kXxSq8c1aKRwGZNqdVaWZ9CpoJJBs' },
  { name: 'ayahuasca', map: 'xKjoUuXUQYLxHAQ4FHf8Wws8NSKZeLzsNmpMxbdd' },
  { name: 'salvia divinorum', map: '3xFPt1SsSfZiWKyx2dqUQoSxpQGWs7bWApBA5yQ1' },
  { name: 'ibogaine', map: 'y8pScJwJhUSRGTcfzu5NJx9HDFJoHahYpczfHQW5' },
  { name: 'awareness', map: 'm3WEUpjspTcwqddz1k6ZtHth2nfJmqZZq8wHqwqg' },
  { name: 'iOS apps', map: '8QUh7V26pBoWjmMFeks2apAGsHqddsq9SsyDvpov' },
  { name: 'pure functions', map: 'Hy1SexHgDAkwdLoBx5jRbYL1i4MszQoH3KnJ8j6v' },
  { name: 'tail recursion', map: 'D1xc931e997zEEXk5DBFGf9qnsGPj2t1D83s1P7z' },
  { name: 'innovation', map: '4r18HsCbKzyqBYEsxch94RHsHxMiWufuqwuqmu3U' },
  { name: 'activation functions', map: 'FEoVZ2JYmzqA8psYXySWNrSstzX7zw2CrsHJszAZ' },
  { name: 'expected value', map: 'BY6ZsiKtLZRTets2gBakqPVMW1DWfyMCuRzU7qLN' },
  { name: 'biases in neural networks', map: 'GuaqvCZceVUsmkLosKWaVNkqUucqp9gp3jUqJ6qE' },
  { name: 'perceptrons', map: 'f5yM1K3bpbbb7cxSqGRwggx8ar5veMcrpusvEUvx' },
  { name: 'vector norms', map: 'AeyYudbBsgionqyMnHeWkqpDJAy6mkohSzjnd3eT' },
  { name: 'logistic regression', map: 'ej4wB4BrBXDwzzrRJXY7YaxFKXV9r5xffqbJiGyz' },
  { name: 'logistic functions', map: 'wZZ43QEzhVEYAS8zfooBMs2j3uWM6wdyHKjGrsdq' },
  { name: 'softmax functions', map: 'CoT86va1KhsrAFH3VzKqJ8SKESjQuppcnwWjYWjd' },
  { name: 'generative learning', map: 'DiSyLnjJcwJq7yybyMVDhCs8qYNdnbqWPyHuxJmT' },
  { name: 'probabilistic classification', map: 'AjeGiYfMvkPPtDzYdjHt6GavwyQ7TxP7mZGoHALb' },
  { name: 'Naive Bayes classifier', map: 'cMCcGaSzRFBP4L8iXxynNqRwJ743KsFDMbYva52Y' },
  { name: 'linear classification', map: 'A4zjzZhvFFqbtzAQWKKAnqpkthhMziYsVcUvRBzD' },
  { name: 'backpropagation through time', map: 'RuRMBJjiHuKSs798qBwnMpzzTthApjtz6Fp4GRoH' },
  { name: 'turing machines', map: 'fsKqqedULwQZSiAHcc4LmqgbJh7TsgCsu32Qo5cG' },
  { name: 'neural turing machines', map: 'pn3yN1Ju11iyp2pyUipPvFFxxuuseasSDJ7QEmzQ' },
  { name: 'organic compounds', map: 'z2qnXBqqzBQH8hYhsXQagUVL4kMeuYiNYp1CSkB3' },
  { name: 'alcohol', map: 'JoGij9qcL6YitqV5Xix4j6CiJYPVXAZQk88ygmim' },
  { name: 'metabolism', map: 'YMJyCwgwna3dszfC62fGxpForxxLXAJyhyWsKmPz' },
  { name: 'fermentation', map: 'E2WMYNh6PtsmHGsZ9VvP5xmz9BBza2oxmm8qZPrh' },
  { name: 'cellular respiration', map: 'pR2dpG3a9i6g539yBTZcbmUgM1n2i1uqhGdbgHbb' },
  { name: 'anaerobic respiration', map: 'WjWQ1v67zNNp6D9qKymVSm6M3p4nzmYJpMCV5EMo' },
  { name: 'inorganic chemistry', map: 'UKxCXUdVxbXCYdDyny9xyqsjvzhssnHsJxLxQwNV' },
  { name: 'polymer chemistry', map: 'drBjeW2VDGhqThiUJqZmAQUqNdxFXiZFqbQsV3pA' },
  { name: 'chemical reactions', map: 'XsF1PBed5d3CcT6XNMWzriuu2WqAzL8yEJzPmZuZ' },
  { name: 'natural selection', map: 'of7mQoAwxybPsXy7zs2gestKHpeu7ozWjokx7RyR' },
  { name: 'bionics', map: 'AYbj6WS4E54bjmkRCoPoWJGyxWZptVw8aEzckhUt' },
  { name: 'circular economy', map: 'xrhJ7uzQDSAP6fePAqMF4CH6vfAQtmHnf2upyM11' },
  { name: 'Casimir effect', map: 'ZVioNpyfhHsRzb1XvzTFgMThxuqgEZ428Sp5gwpY' },
  { name: 'SQLAlchemy', map: 'DjGypZc6jGFYTxkMHXK6gBsgzXLvsEJtwsJjXzkw' },
  { name: 'polynomials', map: 'guZ4HHHbEqiCXc3VpJ2YwW25x8bYcsRsmRSsBPNs' },
  { name: 'quadratic equations', map: '8v59yezgq2GsDNcw8a7cETsPx9VUoxacogDQ3RqD' },
  { name: 'CSS grid layout', map: 'GAyY2suwsJjbyUcZ1fQKbJW31YqiWS4i4EvJaUqr' },
  { name: 'latvian language', map: 'TDxUqW4QKqdpGbesP2kdJj8qayCYyK1NUxcaFMRn' },
  { name: 'PageRank algorithm', map: 'ZN84T6qfxAFR3sKpFcPDpmpvH8BGXGq14Rktx9eU' },
  { name: 'A* search algorithm', map: 'ZViLXVpPyUStsfdsPJxLqdSzU5ssBKxs8KgxbgZ9' },
  { name: 'principle of maximum entropy', map: 'iAvXbj76S6kLqvK3714SsLypBZsUWvtBTZMniGjy' },
  { name: 'journaling', map: 'qYzjHALJeHxXXCgiMYpACACPfqXZhs2sjxu4qkkr' },
  { name: 'travis CI', map: 'HhD9CVU7znbCkVGqgZy39TTrwyV44gvL1t83ZyYS' },
  { name: 'long short term memory', map: '52gwTZrqaRUT3YsdWbJpy1o3jzwEgHpmmjFfaS4y' },
  { name: 'stack data structure', map: 'WyLMGpfxPRbFCpnpXDkuT9BQeCFHssdmEWLeQSfD' },
  { name: 'priority queues', map: 'hpbywTZs65syi1oMrqbsdSx8duZi9P7S5KywBc4o' },
  { name: 'disjoint sets', map: 'bSM3gowBhs9pF49RtSsxaBc98hXH5KmJ7uTZxJFo' },
  { name: 'heap data structures', map: 'f8syN1QxAoDfJJ1SpZJQZtcwsLy6XnXpax5xZVkf' },
  { name: 'binary heaps', map: 'zwPUHD2eFWEYLDqpYz3Ex24WKKNgopNyj9v2cuNy' },
  { name: 'rasterisation', map: 'nTw9yM3CKCyyYFCMZCPx2gSNeMfBD2MnLrfzJgUj' },
  { name: 'search engine marketing', map: 'q77uXuVnDXsuyarmeyptJ4LdH1JEp4tXYqpwPy8p' },
  { name: 'fear', map: 'HbgkWg4UagkAJeYsK1b1povZABCCQEbiq1pQ9G7g' },
  { name: 'wars', map: 'qUxwdYBqSmUBAqbPzAzAmfKS8DRmPeLDa5fwCamn' },
  { name: 'pandemics', map: 'xdfbY21ieH27zfkfz24stsxmKcJdVpNE2V7Nqoyq' },
  { name: 'terrorism', map: 'yDyjXnFMcNB6kx9BF67DF9yxaQhnSD23rXkux7M7' },
  { name: 'sociobiology', map: 'HrYn2jTUvdxhyS4d99osKq57y6B3qLvhEgx5hHuH' },
  { name: 'zoology', map: 'FHbcvFYwijDQyUysztxAezwHHyeySvyJYEgKRbwD' },
  { name: 'mammals', map: 'smDs43pktK86zHCaFykkFQezktkTxgQfupzMPqpW' },
  { name: 'fish', map: 'WUnPJrT6jkVC35JpCzvDYbgVwjeM3tgFhszU4NRg' },
  { name: 'amphibians', map: 'VK7fUGCzQLrwGs8wqjsyouAYEbFS4i2apWbRqaHq' },
  { name: 'birds', map: 'dhLXYMuFqK9QxAPJ5dNibSW7gsFxTYpEpM5k1txF' },
  { name: 'fully convolutional networks', map: '3DyufWoW25T6mikzx7A8xEn6yZkzKprqhYcwBed4' },
  { name: 'money', map: 'yAZ7G3uVCfPdGTDrkw4UCKeLzrDwSAxtQdgxPZqX' },
  { name: 'financial services', map: 'NbyqqwkwyrxWbSXsEQvT8d8eScj1WQggqrVnfm16' },
  { name: 'currency', map: 'isCsKjcsNVJsKMFusqzyr5VGH2gfWfprDAJmkQeQ' },
  { name: 'foreign exchange market', map: 'xE3T8XfKaEFe5qspw1ZCQV646aqYjYxnv6HHJDzo' },
  { name: 'methodology', map: 'EKSN4nosKsKP96x2r5a4BbhyxryspJgfsqzbkd6k' },
  { name: 'data quality', map: 'bbBJxzQKAue5vrKrEGSUuHis6zZgdksZsXPFvJr6' },
  { name: 'origami', map: 'fznewSvqafFzR9jHXaNtpYBfqxs3rJQrFxnmptpt' },
  { name: 'projective geometry', map: 'yzPKAf5JQp7gXjKp3xGpTsHsozDb91H2TiwrYMjo' },
  { name: 'coordinate systems', map: 'ktEqnbdwjqotWTByEUFRv26PWqR75X5WNKisGBqy' },
  { name: 'topological spaces', map: 'pDGVyKwitFBiZzjxVdoGWpWyN3vF4897uZ84qQMz' },
  { name: 'euclidean space', map: 'SrsyQKwcAuCBFpTYzx3HuNeY243PrxkEi6Jws5Tc' },
  { name: 'geometric algebra', map: 'vz5bfPa6EmxD2aneYQXgGtFrEHXbaYgp7cnngCm1' },
  { name: 'Hilbert spaces', map: 'wVyaVyxWqfpg4p3vUE4pMWr3upNvENMhCy5AzQ2w' },
  { name: 'inner product space', map: 'xkgDGA9fVmZRaQUtzbASAPYqzj6h684tq3pnUf8v' },
  { name: 'normed vector space', map: 'Sp6J1NqUH7Wp2sLLphaHUHjMDyz88Tff7szq2RKy' },
  { name: 'metric spaces', map: 'wW98xW8rNgJpuKwDLrPpDz98wbjYBET5NppPyzBp' },
  { name: 'optimising compiler', map: '8LRiSdAPc22LqLEVjwWbkRvShMVYjJYzAqVJL3P5' },
  { name: 'distributed databases', map: 'mH5k8YTTF9mL1wmMYqr44pzAwPZWbwv4Mosqq2F6' },
  { name: 'memory hierarchy', map: 'qWop3TAj5xLQSvS9X3Q8LQ2FKfwop4VcwuVsPBSr' },
  { name: 'the things network', map: 'D7U5QYifQ6B7BR12PBBgfqfyVg5KrqRNx453pXEU' },
  { name: 'software design', map: 'W6oKdpNyEGfgapRNqcDoy8kgGWzWxaX3drBhRH76' },
  { name: 'formal methods', map: 'oEPybtr2EpyYrJxBFs5VitZmhM8PXht19NxfpycN' },
  { name: 'partial differential equations', map: 'go8XB2orXNE4pGxs5pcM7sLVVfPw7Tqtw3d3pZam' },
  { name: 'solid geometry', map: 'R74NirrBaVeTvzYNnvs6spAJMzdRkYr6gc5ps2Mi' },
  { name: 'polyhedrons', map: 'e6p6HvsyNLasayiba9QNCkysyawtRCeroBqK9uR1' },
  { name: 'mesh generation', map: 'tqWiNNbuvM6TpTiyFCFg6xyARLGcJzSH7WxqWpgA' },
  { name: 'marching cubes', map: 'dwtak9AaDxjdwvfMxHq3LNuZZy2gAMEdC1BpignH' },
  { name: 'petri nets', map: 'v9DEzGB56z4Rr3kfXrJhuotwXmGFg33WCxuQf7Lx' },
  { name: 'load balancing', map: 'ZrNy9HuL5Wx2XihyfwFmAgyPsyx4PhkcreS9kP9T' },
  { name: 'algorithm design', map: 'AiVsE6S17nKMCfHh6tNZzTxBbDCjwh1WmTz9zpdj' },
  { name: 'formal verification', map: 'zA23h6bEJzbGgGMLRvsu8p2Ecswq8P2LramtnS8g' },
  { name: 'graphs', map: '4QpoeBu4Jqui6oEs3sJMyjAFd9wWzYRrX8UxxNVw' },
  { name: 'parity games', map: 'cK8JsX2Kt2qBb9brjGtaov7AdTEqaM6mPqD5sVUn' },
  { name: 'libertarianism', map: 'WsmLxFdtH5EF5wcMqVU4rkMBzsd88K6Zp93hZqbF' },
  { name: 'agorism', map: 'WzxkmHoqyZDsoNc4uToFCrYxPsbq2fEqeDoEX6ps' },
  { name: 'political corruption', map: 'rXUJdpRS1UYsGV4pGUspoUhPo88Gppxie4Wq9fTk' },
  { name: 'mesh networks', map: 'y6V76xDPrWR8p7zWqx1sCsFsxnVKE6dCXRth8QdR' },
  { name: 'development economics', map: 'EpkxtYHXyuMJyxspwXNjVFuwE73pVnvyJYj3yBZq' },
  { name: 'decentralisation', map: '8HomguUy4EunAqAyq7TCc5oD7EY96K347jDj8hDs' },
  { name: 'activism', map: 'Cti6TDsLxEQmRyPh5E2zmdm7p6cjDpX7xbxZJ6j8' },
  { name: 'society', map: 'iRc7u3385UyXr1zxiYdkfWCzj5JYyeus7WnX9rhQ' },
  { name: 'social groups', map: 'F2dkeUYD5Dh2VzyyHrxouN8AxKJWsTNhK8zxsvqo' },
  { name: 'group dynamics', map: 'xrZbsGcxxqjY8sWjC32AEpBwZprsjqJyQaMjr3sz' },
  { name: 'cloud storage', map: 'cX52ZLuD5TMEtd5q9mJGra6L2iBDs3hompW1vTdh' },
  { name: 'Storj decentralised cloud storage', map: 'AEvjZxWtqdVkfKMB8Yk6qhFYykmXrisges69q63v' },
  { name: 'application generators', map: 'zLAwA2ov3CLLqZ1VPiebZB5LdBqfzHuyYLSs7jcX' },
  { name: 'Barnes-Hut simulation', map: 'bQiPTJLJhjm7pCybtiz2g8f7hqmMLdRz9btxzUQK' },
  { name: 'electric charge', map: 'dwGm1FYyYYb5fEqjU9yLxqsq89xRsFnHKmBMDDbp' },
  { name: 'Coulomb’s law', map: '88z9zf2hBeoS1tyPxpRB3PuxT7WSjcpZcXx2mxUN' },
  { name: 'rigid body dynamics', map: 'hjPFouUYuNqEMfrYPpP5zd89c7aPxhzTCjkY86td' },
  { name: 'barcodes', map: 'EF3wUzoDzvbYjj4nr8dYhunRGpfPax2vPqNEhRpG' },
  { name: 'QR codes', map: 'QJfjz7zHTp7rzwpub5W3zYxdFHy2g3vKJabp3pwu' },
  { name: 'JHipster generator', map: 'UUYgxBfpDsAjCqwK9r2VTyXA5zHsL4xqhYxsSk8s' },
  { name: 'Yeoman generator', map: 'XbZQDeoRzPpF9LZcyadGCSs9vU9XRuQDmynsNVnP' },
  { name: 'incidence geometry', map: 'xTHDqvYcQ5qh46fkGgCj88B3SKTdjGF6rawxu2qV' },
  { name: 'linear spaces', map: 'swCrJMo4wpksWsm3ckE7hVYV3nGUFKVbPPMgjxts' },
  { name: 'dimensions', map: 'EKZzu4fBwFoGd4s1Dbx2xuEkxMtGkfsi69Duoyv8' },
  { name: 'waves', map: 'odRfVJPx1yy8RDNb6pW3YSAJpSqRQWiv8eXQS6DR' },
  { name: 'mechanical waves', map: 'TQWhKD6kAKExCPhXsgVsSqBPtvrFnpASdX6zuk8R' },
  { name: 'acoustics', map: 'iFwXUQ8r3zz9pqFtaVNajmFDyDGhy4PytzYMWyMR' },
  { name: 'time', map: 'xJReShHdHy4sYXkyf9Um3qZpiTRs7rjjCSfqbDDq' },
  { name: 'time travel', map: 'NFXhpmGtwVqkPx6pa74mQvYYz6oLZheguKBmpqJc' },
  { name: 'time dilation', map: 'iPDf24tbfwuVde5UV7vR99azv3t74c62BZjyxdXL' },
  { name: 'Banach-Tarski paradox', map: 'DUbD2eeDQninHzVEezSJeSsJ7pj72kmsskiP24uG' },
  { name: 'virtual memory', map: 'aGENDpyy42kxkgTafzhqixdDzJVzF4aErS2Fnhpr' },
  { name: 'money laundering', map: 'n9hKqzqM9zSWAP1poGcsSvBdkyoVtnEpqty55sYf' },
  { name: 'live streaming', map: '3Skepdzzuf7SDptvBgQxbapeViybDJnAxphZKnFy' },
  { name: 'orthonormal basis', map: 'KeGhUuNxpnsw8c8FQc94W1fUPk3ngbYRvH5ay9Zk' },
  { name: 'Cantor set', map: 'CPCF88Rar7xWmuEcH8unDfVWjJ8wAMfHTm8625AY' },
  { name: 'general topology', map: 'HQFBdgQEyt5UHWVDhp9xzFWrvfVkbBukjEZGGUtP' },
  { name: 'religion', map: 'XEfmWxMMwAqDbXnMUPmjAmRYx6S3CXJcvyCdp33j' },
  { name: 'paganism', map: 'xugTYschoVGm8k6rpU8hqY9oX9PsczFn2hwpnBqe' },
  { name: 'God', map: 'GbSW5MNg2kiuwVsLnFti6xsHJG7QmoU4MyjpJqxq' },
  { name: 'persuasion', map: 'u9vKcDHhNxPMPcEzqz7cPUjkxiwETv2ysKv321Wp' },
  { name: 'discourse', map: 'wpeoDp28yaAzq8Tbsh2ShxcgzMNFYQ4w6YCKfzH1' },
  { name: 'rhetoric', map: 'by83yzYSuE7D4PLssZVjmwnaR4DGitsBV6GLpdCq' },
  { name: 'wavelets', map: 'Yoq2p8EGNd8pYYG4vvfDgry73inUt4zMqyPqsMMH' },
  { name: 'oscillations', map: 'iK9m6hmGzzCTKFuLyBYkdsj1Rhyo3zCrtizUHuzz' },
  { name: 'wavelet transform', map: '6txr63usB7NxHxudu9zTHPAp7E2LQysTuRsp7Hnh' },
  { name: 'Fourier series', map: 'snoPKRpyz6S5pnPLaMCLThyuFRwdmgvEeKTm9N1p' },
  { name: 'Fourier transform', map: 'nEd1VjyhzgXJ1qLKMq74pBT3taXXyAb18dwq3ccj' },
  { name: 'fractal analysis', map: 'o7tnSsGBTuzazWvcDdMsu9zVnUUszv75sNeLVsgP' },
  { name: 'polytypes', map: '47REANLypbeeurNcPipZfForXPzc6gbmpvkditE5' },
  { name: 'amplitude', map: 'MGppL4QXdqa6CHL67oHHkJ2qE2uyyhRsbMpckFga' },
  { name: 'free will', map: 'zS31APE3nTBWEMGbmfeLzrqn9aYD2ShHcaKuzbYF' },
  { name: 'computer programs', map: 'CZAvRseshKFKFAsLm1VSA1nRV47dWutzrzajmaEF' },
  { name: 'rubik’s cube', map: 'qdyXGnxKTTCNLoxnsHMXGQZyPLqvUxYE6FFxXMEJ' },
  { name: 'universal composability', map: 'Euwuw5HNzCqepF4RX8Y57TeZLSrWD7BHjqZGVPCH' },
  { name: 'league of legends', map: 'FYGAXgY2NyEC6gqeKnGxKomSFTz6wNPqZbSkyPeu' },
]
